// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: enums.proto

/* eslint-disable */

export const protobufPackage = "f1_23";

/** Packet types */
export enum PacketType {
  PACKET_TYPE_UNSPECIFIED = 0,
  PACKET_HEADER = 1,
  PACKET_TYPE_MOTION = 2,
  PACKET_TYPE_SESSION = 3,
  PACKET_TYPE_LAP = 4,
  PACKET_TYPE_EVENT = 5,
  PACKET_TYPE_PARTICIPANTS = 6,
  PACKET_TYPE_CAR_SETUP = 7,
  PACKET_TYPE_CAR_TELEMETRY = 8,
  PACKET_TYPE_CAR_STATUS = 9,
  PACKET_TYPE_FINAL_CLASSIFICATION = 10,
  PACKET_TYPE_LOBBY_INFO = 11,
  PACKET_TYPE_CAR_DAMAGE = 12,
  PACKET_TYPE_SESSION_HISTORY = 13,
  PACKET_TYPE_TYRE_SETS = 14,
  PACKET_TYPE_MOTION_EX = 15,
  UNRECOGNIZED = -1,
}

export function packetTypeFromJSON(object: any): PacketType {
  switch (object) {
    case 0:
    case "PACKET_TYPE_UNSPECIFIED":
      return PacketType.PACKET_TYPE_UNSPECIFIED;
    case 1:
    case "PACKET_HEADER":
      return PacketType.PACKET_HEADER;
    case 2:
    case "PACKET_TYPE_MOTION":
      return PacketType.PACKET_TYPE_MOTION;
    case 3:
    case "PACKET_TYPE_SESSION":
      return PacketType.PACKET_TYPE_SESSION;
    case 4:
    case "PACKET_TYPE_LAP":
      return PacketType.PACKET_TYPE_LAP;
    case 5:
    case "PACKET_TYPE_EVENT":
      return PacketType.PACKET_TYPE_EVENT;
    case 6:
    case "PACKET_TYPE_PARTICIPANTS":
      return PacketType.PACKET_TYPE_PARTICIPANTS;
    case 7:
    case "PACKET_TYPE_CAR_SETUP":
      return PacketType.PACKET_TYPE_CAR_SETUP;
    case 8:
    case "PACKET_TYPE_CAR_TELEMETRY":
      return PacketType.PACKET_TYPE_CAR_TELEMETRY;
    case 9:
    case "PACKET_TYPE_CAR_STATUS":
      return PacketType.PACKET_TYPE_CAR_STATUS;
    case 10:
    case "PACKET_TYPE_FINAL_CLASSIFICATION":
      return PacketType.PACKET_TYPE_FINAL_CLASSIFICATION;
    case 11:
    case "PACKET_TYPE_LOBBY_INFO":
      return PacketType.PACKET_TYPE_LOBBY_INFO;
    case 12:
    case "PACKET_TYPE_CAR_DAMAGE":
      return PacketType.PACKET_TYPE_CAR_DAMAGE;
    case 13:
    case "PACKET_TYPE_SESSION_HISTORY":
      return PacketType.PACKET_TYPE_SESSION_HISTORY;
    case 14:
    case "PACKET_TYPE_TYRE_SETS":
      return PacketType.PACKET_TYPE_TYRE_SETS;
    case 15:
    case "PACKET_TYPE_MOTION_EX":
      return PacketType.PACKET_TYPE_MOTION_EX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PacketType.UNRECOGNIZED;
  }
}

export function packetTypeToJSON(object: PacketType): string {
  switch (object) {
    case PacketType.PACKET_TYPE_UNSPECIFIED:
      return "PACKET_TYPE_UNSPECIFIED";
    case PacketType.PACKET_HEADER:
      return "PACKET_HEADER";
    case PacketType.PACKET_TYPE_MOTION:
      return "PACKET_TYPE_MOTION";
    case PacketType.PACKET_TYPE_SESSION:
      return "PACKET_TYPE_SESSION";
    case PacketType.PACKET_TYPE_LAP:
      return "PACKET_TYPE_LAP";
    case PacketType.PACKET_TYPE_EVENT:
      return "PACKET_TYPE_EVENT";
    case PacketType.PACKET_TYPE_PARTICIPANTS:
      return "PACKET_TYPE_PARTICIPANTS";
    case PacketType.PACKET_TYPE_CAR_SETUP:
      return "PACKET_TYPE_CAR_SETUP";
    case PacketType.PACKET_TYPE_CAR_TELEMETRY:
      return "PACKET_TYPE_CAR_TELEMETRY";
    case PacketType.PACKET_TYPE_CAR_STATUS:
      return "PACKET_TYPE_CAR_STATUS";
    case PacketType.PACKET_TYPE_FINAL_CLASSIFICATION:
      return "PACKET_TYPE_FINAL_CLASSIFICATION";
    case PacketType.PACKET_TYPE_LOBBY_INFO:
      return "PACKET_TYPE_LOBBY_INFO";
    case PacketType.PACKET_TYPE_CAR_DAMAGE:
      return "PACKET_TYPE_CAR_DAMAGE";
    case PacketType.PACKET_TYPE_SESSION_HISTORY:
      return "PACKET_TYPE_SESSION_HISTORY";
    case PacketType.PACKET_TYPE_TYRE_SETS:
      return "PACKET_TYPE_TYRE_SETS";
    case PacketType.PACKET_TYPE_MOTION_EX:
      return "PACKET_TYPE_MOTION_EX";
    case PacketType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Weather conditions */
export enum Weather {
  WEATHER_UNSPECIFIED = 0,
  CLEAR = 1,
  LIGHT_CLOUD = 2,
  OVERCAST = 3,
  LIGHT_RAIN = 4,
  HEAVY_RAIN = 5,
  STORM = 6,
  UNRECOGNIZED = -1,
}

export function weatherFromJSON(object: any): Weather {
  switch (object) {
    case 0:
    case "WEATHER_UNSPECIFIED":
      return Weather.WEATHER_UNSPECIFIED;
    case 1:
    case "CLEAR":
      return Weather.CLEAR;
    case 2:
    case "LIGHT_CLOUD":
      return Weather.LIGHT_CLOUD;
    case 3:
    case "OVERCAST":
      return Weather.OVERCAST;
    case 4:
    case "LIGHT_RAIN":
      return Weather.LIGHT_RAIN;
    case 5:
    case "HEAVY_RAIN":
      return Weather.HEAVY_RAIN;
    case 6:
    case "STORM":
      return Weather.STORM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Weather.UNRECOGNIZED;
  }
}

export function weatherToJSON(object: Weather): string {
  switch (object) {
    case Weather.WEATHER_UNSPECIFIED:
      return "WEATHER_UNSPECIFIED";
    case Weather.CLEAR:
      return "CLEAR";
    case Weather.LIGHT_CLOUD:
      return "LIGHT_CLOUD";
    case Weather.OVERCAST:
      return "OVERCAST";
    case Weather.LIGHT_RAIN:
      return "LIGHT_RAIN";
    case Weather.HEAVY_RAIN:
      return "HEAVY_RAIN";
    case Weather.STORM:
      return "STORM";
    case Weather.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Session types */
export enum SessionType {
  SESSION_TYPE_UNKNOWN = 0,
  P1 = 1,
  P2 = 2,
  P3 = 3,
  SHORT_P = 4,
  Q1 = 5,
  Q2 = 6,
  Q3 = 7,
  SHORT_Q = 8,
  OSQ = 9,
  R = 10,
  R2 = 11,
  R3 = 12,
  TIME_TRIAL = 13,
  UNRECOGNIZED = -1,
}

export function sessionTypeFromJSON(object: any): SessionType {
  switch (object) {
    case 0:
    case "SESSION_TYPE_UNKNOWN":
      return SessionType.SESSION_TYPE_UNKNOWN;
    case 1:
    case "P1":
      return SessionType.P1;
    case 2:
    case "P2":
      return SessionType.P2;
    case 3:
    case "P3":
      return SessionType.P3;
    case 4:
    case "SHORT_P":
      return SessionType.SHORT_P;
    case 5:
    case "Q1":
      return SessionType.Q1;
    case 6:
    case "Q2":
      return SessionType.Q2;
    case 7:
    case "Q3":
      return SessionType.Q3;
    case 8:
    case "SHORT_Q":
      return SessionType.SHORT_Q;
    case 9:
    case "OSQ":
      return SessionType.OSQ;
    case 10:
    case "R":
      return SessionType.R;
    case 11:
    case "R2":
      return SessionType.R2;
    case 12:
    case "R3":
      return SessionType.R3;
    case 13:
    case "TIME_TRIAL":
      return SessionType.TIME_TRIAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SessionType.UNRECOGNIZED;
  }
}

export function sessionTypeToJSON(object: SessionType): string {
  switch (object) {
    case SessionType.SESSION_TYPE_UNKNOWN:
      return "SESSION_TYPE_UNKNOWN";
    case SessionType.P1:
      return "P1";
    case SessionType.P2:
      return "P2";
    case SessionType.P3:
      return "P3";
    case SessionType.SHORT_P:
      return "SHORT_P";
    case SessionType.Q1:
      return "Q1";
    case SessionType.Q2:
      return "Q2";
    case SessionType.Q3:
      return "Q3";
    case SessionType.SHORT_Q:
      return "SHORT_Q";
    case SessionType.OSQ:
      return "OSQ";
    case SessionType.R:
      return "R";
    case SessionType.R2:
      return "R2";
    case SessionType.R3:
      return "R3";
    case SessionType.TIME_TRIAL:
      return "TIME_TRIAL";
    case SessionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Track IDs */
export enum TrackId {
  TRACK_ID_UNKNOWN = 0,
  MELBOURNE = 1,
  PAUL_RICARD = 2,
  SHANGHAI = 3,
  SAKHIR_BAHRAIN = 4,
  CATALUNYA = 5,
  MONACO = 6,
  MONTREAL = 7,
  SILVERSTONE = 8,
  HOCKENHEIM = 9,
  HUNGARORING = 10,
  SPA = 11,
  MONZA = 12,
  SINGAPORE = 13,
  SUZUKA = 14,
  ABU_DHABI = 15,
  TEXAS = 16,
  BRAZIL = 17,
  AUSTRIA = 18,
  SOCHI = 19,
  MEXICO = 20,
  BAKU_AZERBAIJAN = 21,
  SAKHIR_SHORT = 22,
  SILVERSTONE_SHORT = 23,
  TEXAS_SHORT = 24,
  SUZUKA_SHORT = 25,
  HANOI = 26,
  ZANDVOORT = 27,
  IMOLA = 28,
  PORTIMAO = 29,
  JEDDAH = 30,
  MIAMI = 31,
  LAS_VEGAS = 32,
  LOSAIL = 33,
  UNRECOGNIZED = -1,
}

export function trackIdFromJSON(object: any): TrackId {
  switch (object) {
    case 0:
    case "TRACK_ID_UNKNOWN":
      return TrackId.TRACK_ID_UNKNOWN;
    case 1:
    case "MELBOURNE":
      return TrackId.MELBOURNE;
    case 2:
    case "PAUL_RICARD":
      return TrackId.PAUL_RICARD;
    case 3:
    case "SHANGHAI":
      return TrackId.SHANGHAI;
    case 4:
    case "SAKHIR_BAHRAIN":
      return TrackId.SAKHIR_BAHRAIN;
    case 5:
    case "CATALUNYA":
      return TrackId.CATALUNYA;
    case 6:
    case "MONACO":
      return TrackId.MONACO;
    case 7:
    case "MONTREAL":
      return TrackId.MONTREAL;
    case 8:
    case "SILVERSTONE":
      return TrackId.SILVERSTONE;
    case 9:
    case "HOCKENHEIM":
      return TrackId.HOCKENHEIM;
    case 10:
    case "HUNGARORING":
      return TrackId.HUNGARORING;
    case 11:
    case "SPA":
      return TrackId.SPA;
    case 12:
    case "MONZA":
      return TrackId.MONZA;
    case 13:
    case "SINGAPORE":
      return TrackId.SINGAPORE;
    case 14:
    case "SUZUKA":
      return TrackId.SUZUKA;
    case 15:
    case "ABU_DHABI":
      return TrackId.ABU_DHABI;
    case 16:
    case "TEXAS":
      return TrackId.TEXAS;
    case 17:
    case "BRAZIL":
      return TrackId.BRAZIL;
    case 18:
    case "AUSTRIA":
      return TrackId.AUSTRIA;
    case 19:
    case "SOCHI":
      return TrackId.SOCHI;
    case 20:
    case "MEXICO":
      return TrackId.MEXICO;
    case 21:
    case "BAKU_AZERBAIJAN":
      return TrackId.BAKU_AZERBAIJAN;
    case 22:
    case "SAKHIR_SHORT":
      return TrackId.SAKHIR_SHORT;
    case 23:
    case "SILVERSTONE_SHORT":
      return TrackId.SILVERSTONE_SHORT;
    case 24:
    case "TEXAS_SHORT":
      return TrackId.TEXAS_SHORT;
    case 25:
    case "SUZUKA_SHORT":
      return TrackId.SUZUKA_SHORT;
    case 26:
    case "HANOI":
      return TrackId.HANOI;
    case 27:
    case "ZANDVOORT":
      return TrackId.ZANDVOORT;
    case 28:
    case "IMOLA":
      return TrackId.IMOLA;
    case 29:
    case "PORTIMAO":
      return TrackId.PORTIMAO;
    case 30:
    case "JEDDAH":
      return TrackId.JEDDAH;
    case 31:
    case "MIAMI":
      return TrackId.MIAMI;
    case 32:
    case "LAS_VEGAS":
      return TrackId.LAS_VEGAS;
    case 33:
    case "LOSAIL":
      return TrackId.LOSAIL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TrackId.UNRECOGNIZED;
  }
}

export function trackIdToJSON(object: TrackId): string {
  switch (object) {
    case TrackId.TRACK_ID_UNKNOWN:
      return "TRACK_ID_UNKNOWN";
    case TrackId.MELBOURNE:
      return "MELBOURNE";
    case TrackId.PAUL_RICARD:
      return "PAUL_RICARD";
    case TrackId.SHANGHAI:
      return "SHANGHAI";
    case TrackId.SAKHIR_BAHRAIN:
      return "SAKHIR_BAHRAIN";
    case TrackId.CATALUNYA:
      return "CATALUNYA";
    case TrackId.MONACO:
      return "MONACO";
    case TrackId.MONTREAL:
      return "MONTREAL";
    case TrackId.SILVERSTONE:
      return "SILVERSTONE";
    case TrackId.HOCKENHEIM:
      return "HOCKENHEIM";
    case TrackId.HUNGARORING:
      return "HUNGARORING";
    case TrackId.SPA:
      return "SPA";
    case TrackId.MONZA:
      return "MONZA";
    case TrackId.SINGAPORE:
      return "SINGAPORE";
    case TrackId.SUZUKA:
      return "SUZUKA";
    case TrackId.ABU_DHABI:
      return "ABU_DHABI";
    case TrackId.TEXAS:
      return "TEXAS";
    case TrackId.BRAZIL:
      return "BRAZIL";
    case TrackId.AUSTRIA:
      return "AUSTRIA";
    case TrackId.SOCHI:
      return "SOCHI";
    case TrackId.MEXICO:
      return "MEXICO";
    case TrackId.BAKU_AZERBAIJAN:
      return "BAKU_AZERBAIJAN";
    case TrackId.SAKHIR_SHORT:
      return "SAKHIR_SHORT";
    case TrackId.SILVERSTONE_SHORT:
      return "SILVERSTONE_SHORT";
    case TrackId.TEXAS_SHORT:
      return "TEXAS_SHORT";
    case TrackId.SUZUKA_SHORT:
      return "SUZUKA_SHORT";
    case TrackId.HANOI:
      return "HANOI";
    case TrackId.ZANDVOORT:
      return "ZANDVOORT";
    case TrackId.IMOLA:
      return "IMOLA";
    case TrackId.PORTIMAO:
      return "PORTIMAO";
    case TrackId.JEDDAH:
      return "JEDDAH";
    case TrackId.MIAMI:
      return "MIAMI";
    case TrackId.LAS_VEGAS:
      return "LAS_VEGAS";
    case TrackId.LOSAIL:
      return "LOSAIL";
    case TrackId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Temperature change */
export enum TemperatureChange {
  TEMPERATURE_CHANGE_UNSPECIFIED = 0,
  UP = 1,
  DOWN = 2,
  NO_CHANGE = 3,
  UNRECOGNIZED = -1,
}

export function temperatureChangeFromJSON(object: any): TemperatureChange {
  switch (object) {
    case 0:
    case "TEMPERATURE_CHANGE_UNSPECIFIED":
      return TemperatureChange.TEMPERATURE_CHANGE_UNSPECIFIED;
    case 1:
    case "UP":
      return TemperatureChange.UP;
    case 2:
    case "DOWN":
      return TemperatureChange.DOWN;
    case 3:
    case "NO_CHANGE":
      return TemperatureChange.NO_CHANGE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TemperatureChange.UNRECOGNIZED;
  }
}

export function temperatureChangeToJSON(object: TemperatureChange): string {
  switch (object) {
    case TemperatureChange.TEMPERATURE_CHANGE_UNSPECIFIED:
      return "TEMPERATURE_CHANGE_UNSPECIFIED";
    case TemperatureChange.UP:
      return "UP";
    case TemperatureChange.DOWN:
      return "DOWN";
    case TemperatureChange.NO_CHANGE:
      return "NO_CHANGE";
    case TemperatureChange.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Safety car status */
export enum SafetyCarStatus {
  SAFETY_CAR_STATUS_UNSPECIFIED = 0,
  NO_SAFETY_CAR = 1,
  FULL_SAFETY_CAR = 2,
  VIRTUAL_SAFETY_CAR = 3,
  FORMATION_LAP = 4,
  UNRECOGNIZED = -1,
}

export function safetyCarStatusFromJSON(object: any): SafetyCarStatus {
  switch (object) {
    case 0:
    case "SAFETY_CAR_STATUS_UNSPECIFIED":
      return SafetyCarStatus.SAFETY_CAR_STATUS_UNSPECIFIED;
    case 1:
    case "NO_SAFETY_CAR":
      return SafetyCarStatus.NO_SAFETY_CAR;
    case 2:
    case "FULL_SAFETY_CAR":
      return SafetyCarStatus.FULL_SAFETY_CAR;
    case 3:
    case "VIRTUAL_SAFETY_CAR":
      return SafetyCarStatus.VIRTUAL_SAFETY_CAR;
    case 4:
    case "FORMATION_LAP":
      return SafetyCarStatus.FORMATION_LAP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SafetyCarStatus.UNRECOGNIZED;
  }
}

export function safetyCarStatusToJSON(object: SafetyCarStatus): string {
  switch (object) {
    case SafetyCarStatus.SAFETY_CAR_STATUS_UNSPECIFIED:
      return "SAFETY_CAR_STATUS_UNSPECIFIED";
    case SafetyCarStatus.NO_SAFETY_CAR:
      return "NO_SAFETY_CAR";
    case SafetyCarStatus.FULL_SAFETY_CAR:
      return "FULL_SAFETY_CAR";
    case SafetyCarStatus.VIRTUAL_SAFETY_CAR:
      return "VIRTUAL_SAFETY_CAR";
    case SafetyCarStatus.FORMATION_LAP:
      return "FORMATION_LAP";
    case SafetyCarStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Pit status */
export enum PitStatus {
  PIT_STATUS_NONE = 0,
  PITTING = 1,
  IN_PIT_AREA = 2,
  UNRECOGNIZED = -1,
}

export function pitStatusFromJSON(object: any): PitStatus {
  switch (object) {
    case 0:
    case "PIT_STATUS_NONE":
      return PitStatus.PIT_STATUS_NONE;
    case 1:
    case "PITTING":
      return PitStatus.PITTING;
    case 2:
    case "IN_PIT_AREA":
      return PitStatus.IN_PIT_AREA;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PitStatus.UNRECOGNIZED;
  }
}

export function pitStatusToJSON(object: PitStatus): string {
  switch (object) {
    case PitStatus.PIT_STATUS_NONE:
      return "PIT_STATUS_NONE";
    case PitStatus.PITTING:
      return "PITTING";
    case PitStatus.IN_PIT_AREA:
      return "IN_PIT_AREA";
    case PitStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Sector */
export enum Sector {
  SECTOR_UNSPECIFIED = 0,
  SECTOR1 = 1,
  SECTOR2 = 2,
  SECTOR3 = 3,
  UNRECOGNIZED = -1,
}

export function sectorFromJSON(object: any): Sector {
  switch (object) {
    case 0:
    case "SECTOR_UNSPECIFIED":
      return Sector.SECTOR_UNSPECIFIED;
    case 1:
    case "SECTOR1":
      return Sector.SECTOR1;
    case 2:
    case "SECTOR2":
      return Sector.SECTOR2;
    case 3:
    case "SECTOR3":
      return Sector.SECTOR3;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Sector.UNRECOGNIZED;
  }
}

export function sectorToJSON(object: Sector): string {
  switch (object) {
    case Sector.SECTOR_UNSPECIFIED:
      return "SECTOR_UNSPECIFIED";
    case Sector.SECTOR1:
      return "SECTOR1";
    case Sector.SECTOR2:
      return "SECTOR2";
    case Sector.SECTOR3:
      return "SECTOR3";
    case Sector.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Lap validity */
export enum LapValidity {
  VALID = 0,
  INVALID = 1,
  UNRECOGNIZED = -1,
}

export function lapValidityFromJSON(object: any): LapValidity {
  switch (object) {
    case 0:
    case "VALID":
      return LapValidity.VALID;
    case 1:
    case "INVALID":
      return LapValidity.INVALID;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LapValidity.UNRECOGNIZED;
  }
}

export function lapValidityToJSON(object: LapValidity): string {
  switch (object) {
    case LapValidity.VALID:
      return "VALID";
    case LapValidity.INVALID:
      return "INVALID";
    case LapValidity.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Result status */
export enum ResultStatus {
  RESULT_STATUS_INVALID = 0,
  INACTIVE = 1,
  ACTIVE = 2,
  FINISHED = 3,
  DNF = 4,
  DSQ = 5,
  NOT_CLASSIFIED = 6,
  RETIRED = 7,
  UNRECOGNIZED = -1,
}

export function resultStatusFromJSON(object: any): ResultStatus {
  switch (object) {
    case 0:
    case "RESULT_STATUS_INVALID":
      return ResultStatus.RESULT_STATUS_INVALID;
    case 1:
    case "INACTIVE":
      return ResultStatus.INACTIVE;
    case 2:
    case "ACTIVE":
      return ResultStatus.ACTIVE;
    case 3:
    case "FINISHED":
      return ResultStatus.FINISHED;
    case 4:
    case "DNF":
      return ResultStatus.DNF;
    case 5:
    case "DSQ":
      return ResultStatus.DSQ;
    case 6:
    case "NOT_CLASSIFIED":
      return ResultStatus.NOT_CLASSIFIED;
    case 7:
    case "RETIRED":
      return ResultStatus.RETIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ResultStatus.UNRECOGNIZED;
  }
}

export function resultStatusToJSON(object: ResultStatus): string {
  switch (object) {
    case ResultStatus.RESULT_STATUS_INVALID:
      return "RESULT_STATUS_INVALID";
    case ResultStatus.INACTIVE:
      return "INACTIVE";
    case ResultStatus.ACTIVE:
      return "ACTIVE";
    case ResultStatus.FINISHED:
      return "FINISHED";
    case ResultStatus.DNF:
      return "DNF";
    case ResultStatus.DSQ:
      return "DSQ";
    case ResultStatus.NOT_CLASSIFIED:
      return "NOT_CLASSIFIED";
    case ResultStatus.RETIRED:
      return "RETIRED";
    case ResultStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Pit stop should serve penalty */
export enum PitStopShouldServePenalty {
  NO = 0,
  YES = 1,
  UNRECOGNIZED = -1,
}

export function pitStopShouldServePenaltyFromJSON(object: any): PitStopShouldServePenalty {
  switch (object) {
    case 0:
    case "NO":
      return PitStopShouldServePenalty.NO;
    case 1:
    case "YES":
      return PitStopShouldServePenalty.YES;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PitStopShouldServePenalty.UNRECOGNIZED;
  }
}

export function pitStopShouldServePenaltyToJSON(object: PitStopShouldServePenalty): string {
  switch (object) {
    case PitStopShouldServePenalty.NO:
      return "NO";
    case PitStopShouldServePenalty.YES:
      return "YES";
    case PitStopShouldServePenalty.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Event types for telemetry events */
export enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0,
  SESSION_STARTED = 1,
  SESSION_ENDED = 2,
  FASTEST_LAP = 3,
  RETIREMENT = 4,
  DRS_ENABLED = 5,
  DRS_DISABLED = 6,
  TEAM_MATE_IN_PITS = 7,
  CHEQUERED_FLAG = 8,
  RACE_WINNER = 9,
  PENALTY_ISSUED = 10,
  SPEED_TRAP_TRIGGERED = 11,
  START_LIGHT = 12,
  LIGHTS_OUT = 13,
  DRIVE_THROUGH_SERVED = 14,
  STOP_GO_SERVED = 15,
  FLASHBACK = 16,
  BUTTON_STATUS = 17,
  RED_FLAG = 18,
  OVERTAKE = 19,
  UNKNOWN = 20,
  UNRECOGNIZED = -1,
}

export function eventTypeFromJSON(object: any): EventType {
  switch (object) {
    case 0:
    case "EVENT_TYPE_UNSPECIFIED":
      return EventType.EVENT_TYPE_UNSPECIFIED;
    case 1:
    case "SESSION_STARTED":
      return EventType.SESSION_STARTED;
    case 2:
    case "SESSION_ENDED":
      return EventType.SESSION_ENDED;
    case 3:
    case "FASTEST_LAP":
      return EventType.FASTEST_LAP;
    case 4:
    case "RETIREMENT":
      return EventType.RETIREMENT;
    case 5:
    case "DRS_ENABLED":
      return EventType.DRS_ENABLED;
    case 6:
    case "DRS_DISABLED":
      return EventType.DRS_DISABLED;
    case 7:
    case "TEAM_MATE_IN_PITS":
      return EventType.TEAM_MATE_IN_PITS;
    case 8:
    case "CHEQUERED_FLAG":
      return EventType.CHEQUERED_FLAG;
    case 9:
    case "RACE_WINNER":
      return EventType.RACE_WINNER;
    case 10:
    case "PENALTY_ISSUED":
      return EventType.PENALTY_ISSUED;
    case 11:
    case "SPEED_TRAP_TRIGGERED":
      return EventType.SPEED_TRAP_TRIGGERED;
    case 12:
    case "START_LIGHT":
      return EventType.START_LIGHT;
    case 13:
    case "LIGHTS_OUT":
      return EventType.LIGHTS_OUT;
    case 14:
    case "DRIVE_THROUGH_SERVED":
      return EventType.DRIVE_THROUGH_SERVED;
    case 15:
    case "STOP_GO_SERVED":
      return EventType.STOP_GO_SERVED;
    case 16:
    case "FLASHBACK":
      return EventType.FLASHBACK;
    case 17:
    case "BUTTON_STATUS":
      return EventType.BUTTON_STATUS;
    case 18:
    case "RED_FLAG":
      return EventType.RED_FLAG;
    case 19:
    case "OVERTAKE":
      return EventType.OVERTAKE;
    case 20:
    case "UNKNOWN":
      return EventType.UNKNOWN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EventType.UNRECOGNIZED;
  }
}

export function eventTypeToJSON(object: EventType): string {
  switch (object) {
    case EventType.EVENT_TYPE_UNSPECIFIED:
      return "EVENT_TYPE_UNSPECIFIED";
    case EventType.SESSION_STARTED:
      return "SESSION_STARTED";
    case EventType.SESSION_ENDED:
      return "SESSION_ENDED";
    case EventType.FASTEST_LAP:
      return "FASTEST_LAP";
    case EventType.RETIREMENT:
      return "RETIREMENT";
    case EventType.DRS_ENABLED:
      return "DRS_ENABLED";
    case EventType.DRS_DISABLED:
      return "DRS_DISABLED";
    case EventType.TEAM_MATE_IN_PITS:
      return "TEAM_MATE_IN_PITS";
    case EventType.CHEQUERED_FLAG:
      return "CHEQUERED_FLAG";
    case EventType.RACE_WINNER:
      return "RACE_WINNER";
    case EventType.PENALTY_ISSUED:
      return "PENALTY_ISSUED";
    case EventType.SPEED_TRAP_TRIGGERED:
      return "SPEED_TRAP_TRIGGERED";
    case EventType.START_LIGHT:
      return "START_LIGHT";
    case EventType.LIGHTS_OUT:
      return "LIGHTS_OUT";
    case EventType.DRIVE_THROUGH_SERVED:
      return "DRIVE_THROUGH_SERVED";
    case EventType.STOP_GO_SERVED:
      return "STOP_GO_SERVED";
    case EventType.FLASHBACK:
      return "FLASHBACK";
    case EventType.BUTTON_STATUS:
      return "BUTTON_STATUS";
    case EventType.RED_FLAG:
      return "RED_FLAG";
    case EventType.OVERTAKE:
      return "OVERTAKE";
    case EventType.UNKNOWN:
      return "UNKNOWN";
    case EventType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Penalty types */
export enum PenaltyType {
  PENALTY_TYPE_UNSPECIFIED = 0,
  DRIVE_THROUGH = 1,
  STOP_GO = 2,
  GRID_PENALTY = 3,
  PENALTY_REMINDER = 4,
  TIME_PENALTY = 5,
  WARNING = 6,
  DISQUALIFIED = 7,
  REMOVED_FROM_FORMATION_LAP = 8,
  PARKED_TOO_LONG_TIMER = 9,
  TYRE_REGULATIONS = 10,
  THIS_LAP_INVALIDATED = 11,
  THIS_AND_NEXT_LAP_INVALIDATED = 12,
  THIS_LAP_INVALIDATED_WITHOUT_REASON = 13,
  THIS_AND_NEXT_LAP_INVALIDATED_WITHOUT_REASON = 14,
  THIS_AND_PREVIOUS_LAP_INVALIDATED = 15,
  THIS_AND_PREVIOUS_LAP_INVALIDATED_WITHOUT_REASON = 16,
  RETIRED_PENALTY = 17,
  BLACK_FLAG_TIMER = 18,
  UNRECOGNIZED = -1,
}

export function penaltyTypeFromJSON(object: any): PenaltyType {
  switch (object) {
    case 0:
    case "PENALTY_TYPE_UNSPECIFIED":
      return PenaltyType.PENALTY_TYPE_UNSPECIFIED;
    case 1:
    case "DRIVE_THROUGH":
      return PenaltyType.DRIVE_THROUGH;
    case 2:
    case "STOP_GO":
      return PenaltyType.STOP_GO;
    case 3:
    case "GRID_PENALTY":
      return PenaltyType.GRID_PENALTY;
    case 4:
    case "PENALTY_REMINDER":
      return PenaltyType.PENALTY_REMINDER;
    case 5:
    case "TIME_PENALTY":
      return PenaltyType.TIME_PENALTY;
    case 6:
    case "WARNING":
      return PenaltyType.WARNING;
    case 7:
    case "DISQUALIFIED":
      return PenaltyType.DISQUALIFIED;
    case 8:
    case "REMOVED_FROM_FORMATION_LAP":
      return PenaltyType.REMOVED_FROM_FORMATION_LAP;
    case 9:
    case "PARKED_TOO_LONG_TIMER":
      return PenaltyType.PARKED_TOO_LONG_TIMER;
    case 10:
    case "TYRE_REGULATIONS":
      return PenaltyType.TYRE_REGULATIONS;
    case 11:
    case "THIS_LAP_INVALIDATED":
      return PenaltyType.THIS_LAP_INVALIDATED;
    case 12:
    case "THIS_AND_NEXT_LAP_INVALIDATED":
      return PenaltyType.THIS_AND_NEXT_LAP_INVALIDATED;
    case 13:
    case "THIS_LAP_INVALIDATED_WITHOUT_REASON":
      return PenaltyType.THIS_LAP_INVALIDATED_WITHOUT_REASON;
    case 14:
    case "THIS_AND_NEXT_LAP_INVALIDATED_WITHOUT_REASON":
      return PenaltyType.THIS_AND_NEXT_LAP_INVALIDATED_WITHOUT_REASON;
    case 15:
    case "THIS_AND_PREVIOUS_LAP_INVALIDATED":
      return PenaltyType.THIS_AND_PREVIOUS_LAP_INVALIDATED;
    case 16:
    case "THIS_AND_PREVIOUS_LAP_INVALIDATED_WITHOUT_REASON":
      return PenaltyType.THIS_AND_PREVIOUS_LAP_INVALIDATED_WITHOUT_REASON;
    case 17:
    case "RETIRED_PENALTY":
      return PenaltyType.RETIRED_PENALTY;
    case 18:
    case "BLACK_FLAG_TIMER":
      return PenaltyType.BLACK_FLAG_TIMER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PenaltyType.UNRECOGNIZED;
  }
}

export function penaltyTypeToJSON(object: PenaltyType): string {
  switch (object) {
    case PenaltyType.PENALTY_TYPE_UNSPECIFIED:
      return "PENALTY_TYPE_UNSPECIFIED";
    case PenaltyType.DRIVE_THROUGH:
      return "DRIVE_THROUGH";
    case PenaltyType.STOP_GO:
      return "STOP_GO";
    case PenaltyType.GRID_PENALTY:
      return "GRID_PENALTY";
    case PenaltyType.PENALTY_REMINDER:
      return "PENALTY_REMINDER";
    case PenaltyType.TIME_PENALTY:
      return "TIME_PENALTY";
    case PenaltyType.WARNING:
      return "WARNING";
    case PenaltyType.DISQUALIFIED:
      return "DISQUALIFIED";
    case PenaltyType.REMOVED_FROM_FORMATION_LAP:
      return "REMOVED_FROM_FORMATION_LAP";
    case PenaltyType.PARKED_TOO_LONG_TIMER:
      return "PARKED_TOO_LONG_TIMER";
    case PenaltyType.TYRE_REGULATIONS:
      return "TYRE_REGULATIONS";
    case PenaltyType.THIS_LAP_INVALIDATED:
      return "THIS_LAP_INVALIDATED";
    case PenaltyType.THIS_AND_NEXT_LAP_INVALIDATED:
      return "THIS_AND_NEXT_LAP_INVALIDATED";
    case PenaltyType.THIS_LAP_INVALIDATED_WITHOUT_REASON:
      return "THIS_LAP_INVALIDATED_WITHOUT_REASON";
    case PenaltyType.THIS_AND_NEXT_LAP_INVALIDATED_WITHOUT_REASON:
      return "THIS_AND_NEXT_LAP_INVALIDATED_WITHOUT_REASON";
    case PenaltyType.THIS_AND_PREVIOUS_LAP_INVALIDATED:
      return "THIS_AND_PREVIOUS_LAP_INVALIDATED";
    case PenaltyType.THIS_AND_PREVIOUS_LAP_INVALIDATED_WITHOUT_REASON:
      return "THIS_AND_PREVIOUS_LAP_INVALIDATED_WITHOUT_REASON";
    case PenaltyType.RETIRED_PENALTY:
      return "RETIRED_PENALTY";
    case PenaltyType.BLACK_FLAG_TIMER:
      return "BLACK_FLAG_TIMER";
    case PenaltyType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Infringement types */
export enum InfringementType {
  INFRINGEMENT_TYPE_UNSPECIFIED = 0,
  BLOCKING_BY_SLOW_DRIVING = 1,
  BLOCKING_BY_WRONG_WAY_DRIVING = 2,
  REVERSING_OFF_THE_START_LINE = 3,
  BIG_COLLISION = 4,
  SMALL_COLLISION = 5,
  COLLISION_FAILED_TO_HAND_BACK_POSITION_SINGLE = 6,
  COLLISION_FAILED_TO_HAND_BACK_POSITION_MULTIPLE = 7,
  CORNER_CUTTING_GAINED_TIME = 8,
  CORNER_CUTTING_OVERTAKE_SINGLE = 9,
  CORNER_CUTTING_OVERTAKE_MULTIPLE = 10,
  CROSSED_PIT_EXIT_LANE = 11,
  IGNORING_BLUE_FLAGS = 12,
  IGNORING_YELLOW_FLAGS = 13,
  IGNORING_DRIVE_THROUGH = 14,
  TOO_MANY_DRIVE_THROUGHS = 15,
  DRIVE_THROUGH_REMINDER_SERVE_WITHIN_N_LAPS = 16,
  DRIVE_THROUGH_REMINDER_SERVE_THIS_LAP = 17,
  PIT_LANE_SPEEDING = 18,
  PARKED_FOR_TOO_LONG = 19,
  IGNORING_TYRE_REGULATIONS = 20,
  TOO_MANY_PENALTIES = 21,
  MULTIPLE_WARNINGS = 22,
  APPROACHING_DISQUALIFICATION = 23,
  TYRE_REGULATIONS_SELECT_SINGLE = 24,
  TYRE_REGULATIONS_SELECT_MULTIPLE = 25,
  LAP_INVALIDATED_CORNER_CUTTING = 26,
  LAP_INVALIDATED_RUNNING_WIDE = 27,
  CORNER_CUTTING_RAN_WIDE_GAINED_TIME_MINOR = 28,
  CORNER_CUTTING_RAN_WIDE_GAINED_TIME_SIGNIFICANT = 29,
  CORNER_CUTTING_RAN_WIDE_GAINED_TIME_EXTREME = 30,
  LAP_INVALIDATED_WALL_RIDING = 31,
  LAP_INVALIDATED_FLASHBACK_USED = 32,
  LAP_INVALIDATED_RESET_TO_TRACK = 33,
  BLOCKING_THE_PITLANE = 34,
  JUMP_START = 35,
  SAFETY_CAR_TO_CAR_COLLISION = 36,
  SAFETY_CAR_ILLEGAL_OVERTAKE = 37,
  SAFETY_CAR_EXCEEDING_ALLOWED_PACE = 38,
  VIRTUAL_SAFETY_CAR_EXCEEDING_ALLOWED_PACE = 39,
  FORMATION_LAP_BELOW_ALLOWED_SPEED = 40,
  FORMATION_LAP_PARKING = 41,
  RETIRED_MECHANICAL_FAILURE = 42,
  RETIRED_TERMINALLY_DAMAGED = 43,
  SAFETY_CAR_FALLING_TOO_FAR_BACK = 44,
  BLACK_FLAG_TIMER_INFRINGEMENT = 45,
  UNSERVED_STOP_GO_PENALTY = 46,
  UNSERVED_DRIVE_THROUGH_PENALTY = 47,
  ENGINE_COMPONENT_CHANGE = 48,
  GEARBOX_CHANGE = 49,
  PARC_FERME_CHANGE = 50,
  LEAGUE_GRID_PENALTY = 51,
  RETRY_PENALTY = 52,
  ILLEGAL_TIME_GAIN = 53,
  MANDATORY_PITSTOP = 54,
  ATTRIBUTE_ASSIGNED = 55,
  UNRECOGNIZED = -1,
}

export function infringementTypeFromJSON(object: any): InfringementType {
  switch (object) {
    case 0:
    case "INFRINGEMENT_TYPE_UNSPECIFIED":
      return InfringementType.INFRINGEMENT_TYPE_UNSPECIFIED;
    case 1:
    case "BLOCKING_BY_SLOW_DRIVING":
      return InfringementType.BLOCKING_BY_SLOW_DRIVING;
    case 2:
    case "BLOCKING_BY_WRONG_WAY_DRIVING":
      return InfringementType.BLOCKING_BY_WRONG_WAY_DRIVING;
    case 3:
    case "REVERSING_OFF_THE_START_LINE":
      return InfringementType.REVERSING_OFF_THE_START_LINE;
    case 4:
    case "BIG_COLLISION":
      return InfringementType.BIG_COLLISION;
    case 5:
    case "SMALL_COLLISION":
      return InfringementType.SMALL_COLLISION;
    case 6:
    case "COLLISION_FAILED_TO_HAND_BACK_POSITION_SINGLE":
      return InfringementType.COLLISION_FAILED_TO_HAND_BACK_POSITION_SINGLE;
    case 7:
    case "COLLISION_FAILED_TO_HAND_BACK_POSITION_MULTIPLE":
      return InfringementType.COLLISION_FAILED_TO_HAND_BACK_POSITION_MULTIPLE;
    case 8:
    case "CORNER_CUTTING_GAINED_TIME":
      return InfringementType.CORNER_CUTTING_GAINED_TIME;
    case 9:
    case "CORNER_CUTTING_OVERTAKE_SINGLE":
      return InfringementType.CORNER_CUTTING_OVERTAKE_SINGLE;
    case 10:
    case "CORNER_CUTTING_OVERTAKE_MULTIPLE":
      return InfringementType.CORNER_CUTTING_OVERTAKE_MULTIPLE;
    case 11:
    case "CROSSED_PIT_EXIT_LANE":
      return InfringementType.CROSSED_PIT_EXIT_LANE;
    case 12:
    case "IGNORING_BLUE_FLAGS":
      return InfringementType.IGNORING_BLUE_FLAGS;
    case 13:
    case "IGNORING_YELLOW_FLAGS":
      return InfringementType.IGNORING_YELLOW_FLAGS;
    case 14:
    case "IGNORING_DRIVE_THROUGH":
      return InfringementType.IGNORING_DRIVE_THROUGH;
    case 15:
    case "TOO_MANY_DRIVE_THROUGHS":
      return InfringementType.TOO_MANY_DRIVE_THROUGHS;
    case 16:
    case "DRIVE_THROUGH_REMINDER_SERVE_WITHIN_N_LAPS":
      return InfringementType.DRIVE_THROUGH_REMINDER_SERVE_WITHIN_N_LAPS;
    case 17:
    case "DRIVE_THROUGH_REMINDER_SERVE_THIS_LAP":
      return InfringementType.DRIVE_THROUGH_REMINDER_SERVE_THIS_LAP;
    case 18:
    case "PIT_LANE_SPEEDING":
      return InfringementType.PIT_LANE_SPEEDING;
    case 19:
    case "PARKED_FOR_TOO_LONG":
      return InfringementType.PARKED_FOR_TOO_LONG;
    case 20:
    case "IGNORING_TYRE_REGULATIONS":
      return InfringementType.IGNORING_TYRE_REGULATIONS;
    case 21:
    case "TOO_MANY_PENALTIES":
      return InfringementType.TOO_MANY_PENALTIES;
    case 22:
    case "MULTIPLE_WARNINGS":
      return InfringementType.MULTIPLE_WARNINGS;
    case 23:
    case "APPROACHING_DISQUALIFICATION":
      return InfringementType.APPROACHING_DISQUALIFICATION;
    case 24:
    case "TYRE_REGULATIONS_SELECT_SINGLE":
      return InfringementType.TYRE_REGULATIONS_SELECT_SINGLE;
    case 25:
    case "TYRE_REGULATIONS_SELECT_MULTIPLE":
      return InfringementType.TYRE_REGULATIONS_SELECT_MULTIPLE;
    case 26:
    case "LAP_INVALIDATED_CORNER_CUTTING":
      return InfringementType.LAP_INVALIDATED_CORNER_CUTTING;
    case 27:
    case "LAP_INVALIDATED_RUNNING_WIDE":
      return InfringementType.LAP_INVALIDATED_RUNNING_WIDE;
    case 28:
    case "CORNER_CUTTING_RAN_WIDE_GAINED_TIME_MINOR":
      return InfringementType.CORNER_CUTTING_RAN_WIDE_GAINED_TIME_MINOR;
    case 29:
    case "CORNER_CUTTING_RAN_WIDE_GAINED_TIME_SIGNIFICANT":
      return InfringementType.CORNER_CUTTING_RAN_WIDE_GAINED_TIME_SIGNIFICANT;
    case 30:
    case "CORNER_CUTTING_RAN_WIDE_GAINED_TIME_EXTREME":
      return InfringementType.CORNER_CUTTING_RAN_WIDE_GAINED_TIME_EXTREME;
    case 31:
    case "LAP_INVALIDATED_WALL_RIDING":
      return InfringementType.LAP_INVALIDATED_WALL_RIDING;
    case 32:
    case "LAP_INVALIDATED_FLASHBACK_USED":
      return InfringementType.LAP_INVALIDATED_FLASHBACK_USED;
    case 33:
    case "LAP_INVALIDATED_RESET_TO_TRACK":
      return InfringementType.LAP_INVALIDATED_RESET_TO_TRACK;
    case 34:
    case "BLOCKING_THE_PITLANE":
      return InfringementType.BLOCKING_THE_PITLANE;
    case 35:
    case "JUMP_START":
      return InfringementType.JUMP_START;
    case 36:
    case "SAFETY_CAR_TO_CAR_COLLISION":
      return InfringementType.SAFETY_CAR_TO_CAR_COLLISION;
    case 37:
    case "SAFETY_CAR_ILLEGAL_OVERTAKE":
      return InfringementType.SAFETY_CAR_ILLEGAL_OVERTAKE;
    case 38:
    case "SAFETY_CAR_EXCEEDING_ALLOWED_PACE":
      return InfringementType.SAFETY_CAR_EXCEEDING_ALLOWED_PACE;
    case 39:
    case "VIRTUAL_SAFETY_CAR_EXCEEDING_ALLOWED_PACE":
      return InfringementType.VIRTUAL_SAFETY_CAR_EXCEEDING_ALLOWED_PACE;
    case 40:
    case "FORMATION_LAP_BELOW_ALLOWED_SPEED":
      return InfringementType.FORMATION_LAP_BELOW_ALLOWED_SPEED;
    case 41:
    case "FORMATION_LAP_PARKING":
      return InfringementType.FORMATION_LAP_PARKING;
    case 42:
    case "RETIRED_MECHANICAL_FAILURE":
      return InfringementType.RETIRED_MECHANICAL_FAILURE;
    case 43:
    case "RETIRED_TERMINALLY_DAMAGED":
      return InfringementType.RETIRED_TERMINALLY_DAMAGED;
    case 44:
    case "SAFETY_CAR_FALLING_TOO_FAR_BACK":
      return InfringementType.SAFETY_CAR_FALLING_TOO_FAR_BACK;
    case 45:
    case "BLACK_FLAG_TIMER_INFRINGEMENT":
      return InfringementType.BLACK_FLAG_TIMER_INFRINGEMENT;
    case 46:
    case "UNSERVED_STOP_GO_PENALTY":
      return InfringementType.UNSERVED_STOP_GO_PENALTY;
    case 47:
    case "UNSERVED_DRIVE_THROUGH_PENALTY":
      return InfringementType.UNSERVED_DRIVE_THROUGH_PENALTY;
    case 48:
    case "ENGINE_COMPONENT_CHANGE":
      return InfringementType.ENGINE_COMPONENT_CHANGE;
    case 49:
    case "GEARBOX_CHANGE":
      return InfringementType.GEARBOX_CHANGE;
    case 50:
    case "PARC_FERME_CHANGE":
      return InfringementType.PARC_FERME_CHANGE;
    case 51:
    case "LEAGUE_GRID_PENALTY":
      return InfringementType.LEAGUE_GRID_PENALTY;
    case 52:
    case "RETRY_PENALTY":
      return InfringementType.RETRY_PENALTY;
    case 53:
    case "ILLEGAL_TIME_GAIN":
      return InfringementType.ILLEGAL_TIME_GAIN;
    case 54:
    case "MANDATORY_PITSTOP":
      return InfringementType.MANDATORY_PITSTOP;
    case 55:
    case "ATTRIBUTE_ASSIGNED":
      return InfringementType.ATTRIBUTE_ASSIGNED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return InfringementType.UNRECOGNIZED;
  }
}

export function infringementTypeToJSON(object: InfringementType): string {
  switch (object) {
    case InfringementType.INFRINGEMENT_TYPE_UNSPECIFIED:
      return "INFRINGEMENT_TYPE_UNSPECIFIED";
    case InfringementType.BLOCKING_BY_SLOW_DRIVING:
      return "BLOCKING_BY_SLOW_DRIVING";
    case InfringementType.BLOCKING_BY_WRONG_WAY_DRIVING:
      return "BLOCKING_BY_WRONG_WAY_DRIVING";
    case InfringementType.REVERSING_OFF_THE_START_LINE:
      return "REVERSING_OFF_THE_START_LINE";
    case InfringementType.BIG_COLLISION:
      return "BIG_COLLISION";
    case InfringementType.SMALL_COLLISION:
      return "SMALL_COLLISION";
    case InfringementType.COLLISION_FAILED_TO_HAND_BACK_POSITION_SINGLE:
      return "COLLISION_FAILED_TO_HAND_BACK_POSITION_SINGLE";
    case InfringementType.COLLISION_FAILED_TO_HAND_BACK_POSITION_MULTIPLE:
      return "COLLISION_FAILED_TO_HAND_BACK_POSITION_MULTIPLE";
    case InfringementType.CORNER_CUTTING_GAINED_TIME:
      return "CORNER_CUTTING_GAINED_TIME";
    case InfringementType.CORNER_CUTTING_OVERTAKE_SINGLE:
      return "CORNER_CUTTING_OVERTAKE_SINGLE";
    case InfringementType.CORNER_CUTTING_OVERTAKE_MULTIPLE:
      return "CORNER_CUTTING_OVERTAKE_MULTIPLE";
    case InfringementType.CROSSED_PIT_EXIT_LANE:
      return "CROSSED_PIT_EXIT_LANE";
    case InfringementType.IGNORING_BLUE_FLAGS:
      return "IGNORING_BLUE_FLAGS";
    case InfringementType.IGNORING_YELLOW_FLAGS:
      return "IGNORING_YELLOW_FLAGS";
    case InfringementType.IGNORING_DRIVE_THROUGH:
      return "IGNORING_DRIVE_THROUGH";
    case InfringementType.TOO_MANY_DRIVE_THROUGHS:
      return "TOO_MANY_DRIVE_THROUGHS";
    case InfringementType.DRIVE_THROUGH_REMINDER_SERVE_WITHIN_N_LAPS:
      return "DRIVE_THROUGH_REMINDER_SERVE_WITHIN_N_LAPS";
    case InfringementType.DRIVE_THROUGH_REMINDER_SERVE_THIS_LAP:
      return "DRIVE_THROUGH_REMINDER_SERVE_THIS_LAP";
    case InfringementType.PIT_LANE_SPEEDING:
      return "PIT_LANE_SPEEDING";
    case InfringementType.PARKED_FOR_TOO_LONG:
      return "PARKED_FOR_TOO_LONG";
    case InfringementType.IGNORING_TYRE_REGULATIONS:
      return "IGNORING_TYRE_REGULATIONS";
    case InfringementType.TOO_MANY_PENALTIES:
      return "TOO_MANY_PENALTIES";
    case InfringementType.MULTIPLE_WARNINGS:
      return "MULTIPLE_WARNINGS";
    case InfringementType.APPROACHING_DISQUALIFICATION:
      return "APPROACHING_DISQUALIFICATION";
    case InfringementType.TYRE_REGULATIONS_SELECT_SINGLE:
      return "TYRE_REGULATIONS_SELECT_SINGLE";
    case InfringementType.TYRE_REGULATIONS_SELECT_MULTIPLE:
      return "TYRE_REGULATIONS_SELECT_MULTIPLE";
    case InfringementType.LAP_INVALIDATED_CORNER_CUTTING:
      return "LAP_INVALIDATED_CORNER_CUTTING";
    case InfringementType.LAP_INVALIDATED_RUNNING_WIDE:
      return "LAP_INVALIDATED_RUNNING_WIDE";
    case InfringementType.CORNER_CUTTING_RAN_WIDE_GAINED_TIME_MINOR:
      return "CORNER_CUTTING_RAN_WIDE_GAINED_TIME_MINOR";
    case InfringementType.CORNER_CUTTING_RAN_WIDE_GAINED_TIME_SIGNIFICANT:
      return "CORNER_CUTTING_RAN_WIDE_GAINED_TIME_SIGNIFICANT";
    case InfringementType.CORNER_CUTTING_RAN_WIDE_GAINED_TIME_EXTREME:
      return "CORNER_CUTTING_RAN_WIDE_GAINED_TIME_EXTREME";
    case InfringementType.LAP_INVALIDATED_WALL_RIDING:
      return "LAP_INVALIDATED_WALL_RIDING";
    case InfringementType.LAP_INVALIDATED_FLASHBACK_USED:
      return "LAP_INVALIDATED_FLASHBACK_USED";
    case InfringementType.LAP_INVALIDATED_RESET_TO_TRACK:
      return "LAP_INVALIDATED_RESET_TO_TRACK";
    case InfringementType.BLOCKING_THE_PITLANE:
      return "BLOCKING_THE_PITLANE";
    case InfringementType.JUMP_START:
      return "JUMP_START";
    case InfringementType.SAFETY_CAR_TO_CAR_COLLISION:
      return "SAFETY_CAR_TO_CAR_COLLISION";
    case InfringementType.SAFETY_CAR_ILLEGAL_OVERTAKE:
      return "SAFETY_CAR_ILLEGAL_OVERTAKE";
    case InfringementType.SAFETY_CAR_EXCEEDING_ALLOWED_PACE:
      return "SAFETY_CAR_EXCEEDING_ALLOWED_PACE";
    case InfringementType.VIRTUAL_SAFETY_CAR_EXCEEDING_ALLOWED_PACE:
      return "VIRTUAL_SAFETY_CAR_EXCEEDING_ALLOWED_PACE";
    case InfringementType.FORMATION_LAP_BELOW_ALLOWED_SPEED:
      return "FORMATION_LAP_BELOW_ALLOWED_SPEED";
    case InfringementType.FORMATION_LAP_PARKING:
      return "FORMATION_LAP_PARKING";
    case InfringementType.RETIRED_MECHANICAL_FAILURE:
      return "RETIRED_MECHANICAL_FAILURE";
    case InfringementType.RETIRED_TERMINALLY_DAMAGED:
      return "RETIRED_TERMINALLY_DAMAGED";
    case InfringementType.SAFETY_CAR_FALLING_TOO_FAR_BACK:
      return "SAFETY_CAR_FALLING_TOO_FAR_BACK";
    case InfringementType.BLACK_FLAG_TIMER_INFRINGEMENT:
      return "BLACK_FLAG_TIMER_INFRINGEMENT";
    case InfringementType.UNSERVED_STOP_GO_PENALTY:
      return "UNSERVED_STOP_GO_PENALTY";
    case InfringementType.UNSERVED_DRIVE_THROUGH_PENALTY:
      return "UNSERVED_DRIVE_THROUGH_PENALTY";
    case InfringementType.ENGINE_COMPONENT_CHANGE:
      return "ENGINE_COMPONENT_CHANGE";
    case InfringementType.GEARBOX_CHANGE:
      return "GEARBOX_CHANGE";
    case InfringementType.PARC_FERME_CHANGE:
      return "PARC_FERME_CHANGE";
    case InfringementType.LEAGUE_GRID_PENALTY:
      return "LEAGUE_GRID_PENALTY";
    case InfringementType.RETRY_PENALTY:
      return "RETRY_PENALTY";
    case InfringementType.ILLEGAL_TIME_GAIN:
      return "ILLEGAL_TIME_GAIN";
    case InfringementType.MANDATORY_PITSTOP:
      return "MANDATORY_PITSTOP";
    case InfringementType.ATTRIBUTE_ASSIGNED:
      return "ATTRIBUTE_ASSIGNED";
    case InfringementType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Driver IDs */
export enum DriverId {
  DRIVER_ID_UNKNOWN = 0,
  CARLOS_SAINZ = 1,
  DANIIL_KVYAT = 2,
  DANIEL_RICCIARDO = 3,
  FERNANDO_ALONSO = 4,
  FELIPE_MASSA = 5,
  KIMI_RAIKKONEN = 7,
  LEWIS_HAMILTON = 8,
  MAX_VERSTAPPEN = 10,
  NICO_HULKENBURG = 11,
  KEVIN_MAGNUSSEN = 12,
  ROMAIN_GROSJEAN = 13,
  SEBASTIAN_VETTEL = 14,
  SERGIO_PEREZ = 15,
  VALTTERI_BOTTAS = 16,
  ESTEBAN_OCON = 18,
  LANCE_STROLL = 20,
  ARRON_BARNES = 21,
  MARTIN_GILES = 22,
  ALEX_MURRAY = 23,
  LUCAS_ROTH = 24,
  IGOR_CORREIA = 25,
  SOPHIE_LEVASSEUR = 26,
  JONAS_SCHIFFER = 27,
  ALAIN_FOREST = 28,
  JAY_LETOURNEAU = 29,
  ESTO_SAARI = 30,
  YASAR_ATIYEH = 31,
  CALLISTO_CALABRESI = 32,
  NAOTA_IZUM = 33,
  HOWARD_CLARKE = 34,
  WILHEIM_KAUFMANN = 35,
  MARIE_LAURSEN = 36,
  FLAVIO_NIEVES = 37,
  PETER_BELOUSOV = 38,
  KLIMEK_MICHALSKI = 39,
  SANTIAGO_MORENO = 40,
  BENJAMIN_COPPENS = 41,
  NOAH_VISSER = 42,
  GERT_WALDMULLER = 43,
  JULIAN_QUESADA = 44,
  DANIEL_JONES = 45,
  ARTEM_MARKELOV = 46,
  TADASUKE_MAKINO = 47,
  SEAN_GELAEL = 48,
  NYCK_DE_VRIES = 49,
  JACK_AITKEN = 50,
  GEORGE_RUSSELL = 51,
  MAXIMILIAN_GUNTHER = 52,
  NIREI_FUKUZUMI = 53,
  LUCA_GHIOTTO = 54,
  LANDO_NORRIS = 55,
  SERGIO_SETTE_CAMARA = 56,
  LOUIS_DELETRAZ = 57,
  ANTONIO_FUOCO = 58,
  CHARLES_LECLERC = 59,
  PIERRE_GASLY = 60,
  ALEXANDER_ALBON = 63,
  NICHOLAS_LATIFI = 64,
  DORIAN_BOCCOLACCI = 65,
  NIKO_KARI = 66,
  ROBERTO_MERHI = 67,
  ARJUN_MAINI = 68,
  ALESSIO_LORANDI = 69,
  RUBEN_MEIJER = 70,
  RASHID_NAIR = 71,
  JACK_TREMBLAY = 72,
  DEVON_BUTLER = 73,
  LUKAS_WEBER = 74,
  ANTONIO_GIOVINAZZI = 75,
  ROBERT_KUBICA = 76,
  ALAIN_PROST = 77,
  AYRTON_SENNA = 78,
  NOBUHARU_MATSUSHITA = 79,
  NIKITA_MAZEPIN = 80,
  GUANYA_ZHOU = 81,
  MICK_SCHUMACHER = 82,
  CALLUM_ILOTT = 83,
  JUAN_MANUEL_CORREA = 84,
  JORDAN_KING = 85,
  MAHAVEER_RAGHUNATHAN = 86,
  TATIANA_CALDERON = 87,
  ANTHOINE_HUBERT = 88,
  GUILIANO_ALESI = 89,
  RALPH_BOSCHUNG = 90,
  MICHAEL_SCHUMACHER = 91,
  DAN_TICKTUM = 92,
  MARCUS_ARMSTRONG = 93,
  CHRISTIAN_LUNDGAARD = 94,
  YUKI_TSUNODA = 95,
  JEHAN_DARUVALA = 96,
  GULHERME_SAMAIA = 97,
  PEDRO_PIQUET = 98,
  FELIPE_DRUGOVICH = 99,
  ROBERT_SCHWARTZMAN = 100,
  ROY_NISSANY = 101,
  MARINO_SATO = 102,
  AIDAN_JACKSON = 103,
  CASPER_AKKERMAN = 104,
  JENSON_BUTTON = 110,
  DAVID_COULTHARD = 111,
  NICO_ROSBERG = 112,
  OSCAR_PIASTRI = 113,
  LIAM_LAWSON = 114,
  JURI_VIPS = 115,
  THEO_POURCHAIRE = 116,
  RICHARD_VERSCHOOR = 117,
  LIRIM_ZENDELI = 118,
  DAVID_BECKMANN = 119,
  ALESSIO_DELEDDA = 122,
  BENT_VISCAAL = 123,
  ENZO_FITTIPALDI = 124,
  MARK_WEBBER = 126,
  JACQUES_VILLENEUVE = 127,
  CALLIE_MAYER = 128,
  NOAH_BELL = 129,
  JAKE_HUGHES = 130,
  FREDERIK_VESTI = 131,
  OLLI_CALDWELL = 132,
  LOGAN_SARGEANT = 133,
  CEM_BOLUKBASI = 134,
  AYUMU_IWASA = 135,
  CLEMENT_NOVALAK = 136,
  JACK_DOOHAN = 137,
  AMAURY_CORDEEL = 138,
  DENNIS_HAUGER = 139,
  CALAN_WILLIAMS = 140,
  JAMIE_CHADWICK = 141,
  KAMUI_KOBAYASHI = 142,
  PASTOR_MALDONADO = 143,
  MIKA_HAKKINEN = 144,
  NIGEL_MANSELL = 145,
  UNRECOGNIZED = -1,
}

export function driverIdFromJSON(object: any): DriverId {
  switch (object) {
    case 0:
    case "DRIVER_ID_UNKNOWN":
      return DriverId.DRIVER_ID_UNKNOWN;
    case 1:
    case "CARLOS_SAINZ":
      return DriverId.CARLOS_SAINZ;
    case 2:
    case "DANIIL_KVYAT":
      return DriverId.DANIIL_KVYAT;
    case 3:
    case "DANIEL_RICCIARDO":
      return DriverId.DANIEL_RICCIARDO;
    case 4:
    case "FERNANDO_ALONSO":
      return DriverId.FERNANDO_ALONSO;
    case 5:
    case "FELIPE_MASSA":
      return DriverId.FELIPE_MASSA;
    case 7:
    case "KIMI_RAIKKONEN":
      return DriverId.KIMI_RAIKKONEN;
    case 8:
    case "LEWIS_HAMILTON":
      return DriverId.LEWIS_HAMILTON;
    case 10:
    case "MAX_VERSTAPPEN":
      return DriverId.MAX_VERSTAPPEN;
    case 11:
    case "NICO_HULKENBURG":
      return DriverId.NICO_HULKENBURG;
    case 12:
    case "KEVIN_MAGNUSSEN":
      return DriverId.KEVIN_MAGNUSSEN;
    case 13:
    case "ROMAIN_GROSJEAN":
      return DriverId.ROMAIN_GROSJEAN;
    case 14:
    case "SEBASTIAN_VETTEL":
      return DriverId.SEBASTIAN_VETTEL;
    case 15:
    case "SERGIO_PEREZ":
      return DriverId.SERGIO_PEREZ;
    case 16:
    case "VALTTERI_BOTTAS":
      return DriverId.VALTTERI_BOTTAS;
    case 18:
    case "ESTEBAN_OCON":
      return DriverId.ESTEBAN_OCON;
    case 20:
    case "LANCE_STROLL":
      return DriverId.LANCE_STROLL;
    case 21:
    case "ARRON_BARNES":
      return DriverId.ARRON_BARNES;
    case 22:
    case "MARTIN_GILES":
      return DriverId.MARTIN_GILES;
    case 23:
    case "ALEX_MURRAY":
      return DriverId.ALEX_MURRAY;
    case 24:
    case "LUCAS_ROTH":
      return DriverId.LUCAS_ROTH;
    case 25:
    case "IGOR_CORREIA":
      return DriverId.IGOR_CORREIA;
    case 26:
    case "SOPHIE_LEVASSEUR":
      return DriverId.SOPHIE_LEVASSEUR;
    case 27:
    case "JONAS_SCHIFFER":
      return DriverId.JONAS_SCHIFFER;
    case 28:
    case "ALAIN_FOREST":
      return DriverId.ALAIN_FOREST;
    case 29:
    case "JAY_LETOURNEAU":
      return DriverId.JAY_LETOURNEAU;
    case 30:
    case "ESTO_SAARI":
      return DriverId.ESTO_SAARI;
    case 31:
    case "YASAR_ATIYEH":
      return DriverId.YASAR_ATIYEH;
    case 32:
    case "CALLISTO_CALABRESI":
      return DriverId.CALLISTO_CALABRESI;
    case 33:
    case "NAOTA_IZUM":
      return DriverId.NAOTA_IZUM;
    case 34:
    case "HOWARD_CLARKE":
      return DriverId.HOWARD_CLARKE;
    case 35:
    case "WILHEIM_KAUFMANN":
      return DriverId.WILHEIM_KAUFMANN;
    case 36:
    case "MARIE_LAURSEN":
      return DriverId.MARIE_LAURSEN;
    case 37:
    case "FLAVIO_NIEVES":
      return DriverId.FLAVIO_NIEVES;
    case 38:
    case "PETER_BELOUSOV":
      return DriverId.PETER_BELOUSOV;
    case 39:
    case "KLIMEK_MICHALSKI":
      return DriverId.KLIMEK_MICHALSKI;
    case 40:
    case "SANTIAGO_MORENO":
      return DriverId.SANTIAGO_MORENO;
    case 41:
    case "BENJAMIN_COPPENS":
      return DriverId.BENJAMIN_COPPENS;
    case 42:
    case "NOAH_VISSER":
      return DriverId.NOAH_VISSER;
    case 43:
    case "GERT_WALDMULLER":
      return DriverId.GERT_WALDMULLER;
    case 44:
    case "JULIAN_QUESADA":
      return DriverId.JULIAN_QUESADA;
    case 45:
    case "DANIEL_JONES":
      return DriverId.DANIEL_JONES;
    case 46:
    case "ARTEM_MARKELOV":
      return DriverId.ARTEM_MARKELOV;
    case 47:
    case "TADASUKE_MAKINO":
      return DriverId.TADASUKE_MAKINO;
    case 48:
    case "SEAN_GELAEL":
      return DriverId.SEAN_GELAEL;
    case 49:
    case "NYCK_DE_VRIES":
      return DriverId.NYCK_DE_VRIES;
    case 50:
    case "JACK_AITKEN":
      return DriverId.JACK_AITKEN;
    case 51:
    case "GEORGE_RUSSELL":
      return DriverId.GEORGE_RUSSELL;
    case 52:
    case "MAXIMILIAN_GUNTHER":
      return DriverId.MAXIMILIAN_GUNTHER;
    case 53:
    case "NIREI_FUKUZUMI":
      return DriverId.NIREI_FUKUZUMI;
    case 54:
    case "LUCA_GHIOTTO":
      return DriverId.LUCA_GHIOTTO;
    case 55:
    case "LANDO_NORRIS":
      return DriverId.LANDO_NORRIS;
    case 56:
    case "SERGIO_SETTE_CAMARA":
      return DriverId.SERGIO_SETTE_CAMARA;
    case 57:
    case "LOUIS_DELETRAZ":
      return DriverId.LOUIS_DELETRAZ;
    case 58:
    case "ANTONIO_FUOCO":
      return DriverId.ANTONIO_FUOCO;
    case 59:
    case "CHARLES_LECLERC":
      return DriverId.CHARLES_LECLERC;
    case 60:
    case "PIERRE_GASLY":
      return DriverId.PIERRE_GASLY;
    case 63:
    case "ALEXANDER_ALBON":
      return DriverId.ALEXANDER_ALBON;
    case 64:
    case "NICHOLAS_LATIFI":
      return DriverId.NICHOLAS_LATIFI;
    case 65:
    case "DORIAN_BOCCOLACCI":
      return DriverId.DORIAN_BOCCOLACCI;
    case 66:
    case "NIKO_KARI":
      return DriverId.NIKO_KARI;
    case 67:
    case "ROBERTO_MERHI":
      return DriverId.ROBERTO_MERHI;
    case 68:
    case "ARJUN_MAINI":
      return DriverId.ARJUN_MAINI;
    case 69:
    case "ALESSIO_LORANDI":
      return DriverId.ALESSIO_LORANDI;
    case 70:
    case "RUBEN_MEIJER":
      return DriverId.RUBEN_MEIJER;
    case 71:
    case "RASHID_NAIR":
      return DriverId.RASHID_NAIR;
    case 72:
    case "JACK_TREMBLAY":
      return DriverId.JACK_TREMBLAY;
    case 73:
    case "DEVON_BUTLER":
      return DriverId.DEVON_BUTLER;
    case 74:
    case "LUKAS_WEBER":
      return DriverId.LUKAS_WEBER;
    case 75:
    case "ANTONIO_GIOVINAZZI":
      return DriverId.ANTONIO_GIOVINAZZI;
    case 76:
    case "ROBERT_KUBICA":
      return DriverId.ROBERT_KUBICA;
    case 77:
    case "ALAIN_PROST":
      return DriverId.ALAIN_PROST;
    case 78:
    case "AYRTON_SENNA":
      return DriverId.AYRTON_SENNA;
    case 79:
    case "NOBUHARU_MATSUSHITA":
      return DriverId.NOBUHARU_MATSUSHITA;
    case 80:
    case "NIKITA_MAZEPIN":
      return DriverId.NIKITA_MAZEPIN;
    case 81:
    case "GUANYA_ZHOU":
      return DriverId.GUANYA_ZHOU;
    case 82:
    case "MICK_SCHUMACHER":
      return DriverId.MICK_SCHUMACHER;
    case 83:
    case "CALLUM_ILOTT":
      return DriverId.CALLUM_ILOTT;
    case 84:
    case "JUAN_MANUEL_CORREA":
      return DriverId.JUAN_MANUEL_CORREA;
    case 85:
    case "JORDAN_KING":
      return DriverId.JORDAN_KING;
    case 86:
    case "MAHAVEER_RAGHUNATHAN":
      return DriverId.MAHAVEER_RAGHUNATHAN;
    case 87:
    case "TATIANA_CALDERON":
      return DriverId.TATIANA_CALDERON;
    case 88:
    case "ANTHOINE_HUBERT":
      return DriverId.ANTHOINE_HUBERT;
    case 89:
    case "GUILIANO_ALESI":
      return DriverId.GUILIANO_ALESI;
    case 90:
    case "RALPH_BOSCHUNG":
      return DriverId.RALPH_BOSCHUNG;
    case 91:
    case "MICHAEL_SCHUMACHER":
      return DriverId.MICHAEL_SCHUMACHER;
    case 92:
    case "DAN_TICKTUM":
      return DriverId.DAN_TICKTUM;
    case 93:
    case "MARCUS_ARMSTRONG":
      return DriverId.MARCUS_ARMSTRONG;
    case 94:
    case "CHRISTIAN_LUNDGAARD":
      return DriverId.CHRISTIAN_LUNDGAARD;
    case 95:
    case "YUKI_TSUNODA":
      return DriverId.YUKI_TSUNODA;
    case 96:
    case "JEHAN_DARUVALA":
      return DriverId.JEHAN_DARUVALA;
    case 97:
    case "GULHERME_SAMAIA":
      return DriverId.GULHERME_SAMAIA;
    case 98:
    case "PEDRO_PIQUET":
      return DriverId.PEDRO_PIQUET;
    case 99:
    case "FELIPE_DRUGOVICH":
      return DriverId.FELIPE_DRUGOVICH;
    case 100:
    case "ROBERT_SCHWARTZMAN":
      return DriverId.ROBERT_SCHWARTZMAN;
    case 101:
    case "ROY_NISSANY":
      return DriverId.ROY_NISSANY;
    case 102:
    case "MARINO_SATO":
      return DriverId.MARINO_SATO;
    case 103:
    case "AIDAN_JACKSON":
      return DriverId.AIDAN_JACKSON;
    case 104:
    case "CASPER_AKKERMAN":
      return DriverId.CASPER_AKKERMAN;
    case 110:
    case "JENSON_BUTTON":
      return DriverId.JENSON_BUTTON;
    case 111:
    case "DAVID_COULTHARD":
      return DriverId.DAVID_COULTHARD;
    case 112:
    case "NICO_ROSBERG":
      return DriverId.NICO_ROSBERG;
    case 113:
    case "OSCAR_PIASTRI":
      return DriverId.OSCAR_PIASTRI;
    case 114:
    case "LIAM_LAWSON":
      return DriverId.LIAM_LAWSON;
    case 115:
    case "JURI_VIPS":
      return DriverId.JURI_VIPS;
    case 116:
    case "THEO_POURCHAIRE":
      return DriverId.THEO_POURCHAIRE;
    case 117:
    case "RICHARD_VERSCHOOR":
      return DriverId.RICHARD_VERSCHOOR;
    case 118:
    case "LIRIM_ZENDELI":
      return DriverId.LIRIM_ZENDELI;
    case 119:
    case "DAVID_BECKMANN":
      return DriverId.DAVID_BECKMANN;
    case 122:
    case "ALESSIO_DELEDDA":
      return DriverId.ALESSIO_DELEDDA;
    case 123:
    case "BENT_VISCAAL":
      return DriverId.BENT_VISCAAL;
    case 124:
    case "ENZO_FITTIPALDI":
      return DriverId.ENZO_FITTIPALDI;
    case 126:
    case "MARK_WEBBER":
      return DriverId.MARK_WEBBER;
    case 127:
    case "JACQUES_VILLENEUVE":
      return DriverId.JACQUES_VILLENEUVE;
    case 128:
    case "CALLIE_MAYER":
      return DriverId.CALLIE_MAYER;
    case 129:
    case "NOAH_BELL":
      return DriverId.NOAH_BELL;
    case 130:
    case "JAKE_HUGHES":
      return DriverId.JAKE_HUGHES;
    case 131:
    case "FREDERIK_VESTI":
      return DriverId.FREDERIK_VESTI;
    case 132:
    case "OLLI_CALDWELL":
      return DriverId.OLLI_CALDWELL;
    case 133:
    case "LOGAN_SARGEANT":
      return DriverId.LOGAN_SARGEANT;
    case 134:
    case "CEM_BOLUKBASI":
      return DriverId.CEM_BOLUKBASI;
    case 135:
    case "AYUMU_IWASA":
      return DriverId.AYUMU_IWASA;
    case 136:
    case "CLEMENT_NOVALAK":
      return DriverId.CLEMENT_NOVALAK;
    case 137:
    case "JACK_DOOHAN":
      return DriverId.JACK_DOOHAN;
    case 138:
    case "AMAURY_CORDEEL":
      return DriverId.AMAURY_CORDEEL;
    case 139:
    case "DENNIS_HAUGER":
      return DriverId.DENNIS_HAUGER;
    case 140:
    case "CALAN_WILLIAMS":
      return DriverId.CALAN_WILLIAMS;
    case 141:
    case "JAMIE_CHADWICK":
      return DriverId.JAMIE_CHADWICK;
    case 142:
    case "KAMUI_KOBAYASHI":
      return DriverId.KAMUI_KOBAYASHI;
    case 143:
    case "PASTOR_MALDONADO":
      return DriverId.PASTOR_MALDONADO;
    case 144:
    case "MIKA_HAKKINEN":
      return DriverId.MIKA_HAKKINEN;
    case 145:
    case "NIGEL_MANSELL":
      return DriverId.NIGEL_MANSELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DriverId.UNRECOGNIZED;
  }
}

export function driverIdToJSON(object: DriverId): string {
  switch (object) {
    case DriverId.DRIVER_ID_UNKNOWN:
      return "DRIVER_ID_UNKNOWN";
    case DriverId.CARLOS_SAINZ:
      return "CARLOS_SAINZ";
    case DriverId.DANIIL_KVYAT:
      return "DANIIL_KVYAT";
    case DriverId.DANIEL_RICCIARDO:
      return "DANIEL_RICCIARDO";
    case DriverId.FERNANDO_ALONSO:
      return "FERNANDO_ALONSO";
    case DriverId.FELIPE_MASSA:
      return "FELIPE_MASSA";
    case DriverId.KIMI_RAIKKONEN:
      return "KIMI_RAIKKONEN";
    case DriverId.LEWIS_HAMILTON:
      return "LEWIS_HAMILTON";
    case DriverId.MAX_VERSTAPPEN:
      return "MAX_VERSTAPPEN";
    case DriverId.NICO_HULKENBURG:
      return "NICO_HULKENBURG";
    case DriverId.KEVIN_MAGNUSSEN:
      return "KEVIN_MAGNUSSEN";
    case DriverId.ROMAIN_GROSJEAN:
      return "ROMAIN_GROSJEAN";
    case DriverId.SEBASTIAN_VETTEL:
      return "SEBASTIAN_VETTEL";
    case DriverId.SERGIO_PEREZ:
      return "SERGIO_PEREZ";
    case DriverId.VALTTERI_BOTTAS:
      return "VALTTERI_BOTTAS";
    case DriverId.ESTEBAN_OCON:
      return "ESTEBAN_OCON";
    case DriverId.LANCE_STROLL:
      return "LANCE_STROLL";
    case DriverId.ARRON_BARNES:
      return "ARRON_BARNES";
    case DriverId.MARTIN_GILES:
      return "MARTIN_GILES";
    case DriverId.ALEX_MURRAY:
      return "ALEX_MURRAY";
    case DriverId.LUCAS_ROTH:
      return "LUCAS_ROTH";
    case DriverId.IGOR_CORREIA:
      return "IGOR_CORREIA";
    case DriverId.SOPHIE_LEVASSEUR:
      return "SOPHIE_LEVASSEUR";
    case DriverId.JONAS_SCHIFFER:
      return "JONAS_SCHIFFER";
    case DriverId.ALAIN_FOREST:
      return "ALAIN_FOREST";
    case DriverId.JAY_LETOURNEAU:
      return "JAY_LETOURNEAU";
    case DriverId.ESTO_SAARI:
      return "ESTO_SAARI";
    case DriverId.YASAR_ATIYEH:
      return "YASAR_ATIYEH";
    case DriverId.CALLISTO_CALABRESI:
      return "CALLISTO_CALABRESI";
    case DriverId.NAOTA_IZUM:
      return "NAOTA_IZUM";
    case DriverId.HOWARD_CLARKE:
      return "HOWARD_CLARKE";
    case DriverId.WILHEIM_KAUFMANN:
      return "WILHEIM_KAUFMANN";
    case DriverId.MARIE_LAURSEN:
      return "MARIE_LAURSEN";
    case DriverId.FLAVIO_NIEVES:
      return "FLAVIO_NIEVES";
    case DriverId.PETER_BELOUSOV:
      return "PETER_BELOUSOV";
    case DriverId.KLIMEK_MICHALSKI:
      return "KLIMEK_MICHALSKI";
    case DriverId.SANTIAGO_MORENO:
      return "SANTIAGO_MORENO";
    case DriverId.BENJAMIN_COPPENS:
      return "BENJAMIN_COPPENS";
    case DriverId.NOAH_VISSER:
      return "NOAH_VISSER";
    case DriverId.GERT_WALDMULLER:
      return "GERT_WALDMULLER";
    case DriverId.JULIAN_QUESADA:
      return "JULIAN_QUESADA";
    case DriverId.DANIEL_JONES:
      return "DANIEL_JONES";
    case DriverId.ARTEM_MARKELOV:
      return "ARTEM_MARKELOV";
    case DriverId.TADASUKE_MAKINO:
      return "TADASUKE_MAKINO";
    case DriverId.SEAN_GELAEL:
      return "SEAN_GELAEL";
    case DriverId.NYCK_DE_VRIES:
      return "NYCK_DE_VRIES";
    case DriverId.JACK_AITKEN:
      return "JACK_AITKEN";
    case DriverId.GEORGE_RUSSELL:
      return "GEORGE_RUSSELL";
    case DriverId.MAXIMILIAN_GUNTHER:
      return "MAXIMILIAN_GUNTHER";
    case DriverId.NIREI_FUKUZUMI:
      return "NIREI_FUKUZUMI";
    case DriverId.LUCA_GHIOTTO:
      return "LUCA_GHIOTTO";
    case DriverId.LANDO_NORRIS:
      return "LANDO_NORRIS";
    case DriverId.SERGIO_SETTE_CAMARA:
      return "SERGIO_SETTE_CAMARA";
    case DriverId.LOUIS_DELETRAZ:
      return "LOUIS_DELETRAZ";
    case DriverId.ANTONIO_FUOCO:
      return "ANTONIO_FUOCO";
    case DriverId.CHARLES_LECLERC:
      return "CHARLES_LECLERC";
    case DriverId.PIERRE_GASLY:
      return "PIERRE_GASLY";
    case DriverId.ALEXANDER_ALBON:
      return "ALEXANDER_ALBON";
    case DriverId.NICHOLAS_LATIFI:
      return "NICHOLAS_LATIFI";
    case DriverId.DORIAN_BOCCOLACCI:
      return "DORIAN_BOCCOLACCI";
    case DriverId.NIKO_KARI:
      return "NIKO_KARI";
    case DriverId.ROBERTO_MERHI:
      return "ROBERTO_MERHI";
    case DriverId.ARJUN_MAINI:
      return "ARJUN_MAINI";
    case DriverId.ALESSIO_LORANDI:
      return "ALESSIO_LORANDI";
    case DriverId.RUBEN_MEIJER:
      return "RUBEN_MEIJER";
    case DriverId.RASHID_NAIR:
      return "RASHID_NAIR";
    case DriverId.JACK_TREMBLAY:
      return "JACK_TREMBLAY";
    case DriverId.DEVON_BUTLER:
      return "DEVON_BUTLER";
    case DriverId.LUKAS_WEBER:
      return "LUKAS_WEBER";
    case DriverId.ANTONIO_GIOVINAZZI:
      return "ANTONIO_GIOVINAZZI";
    case DriverId.ROBERT_KUBICA:
      return "ROBERT_KUBICA";
    case DriverId.ALAIN_PROST:
      return "ALAIN_PROST";
    case DriverId.AYRTON_SENNA:
      return "AYRTON_SENNA";
    case DriverId.NOBUHARU_MATSUSHITA:
      return "NOBUHARU_MATSUSHITA";
    case DriverId.NIKITA_MAZEPIN:
      return "NIKITA_MAZEPIN";
    case DriverId.GUANYA_ZHOU:
      return "GUANYA_ZHOU";
    case DriverId.MICK_SCHUMACHER:
      return "MICK_SCHUMACHER";
    case DriverId.CALLUM_ILOTT:
      return "CALLUM_ILOTT";
    case DriverId.JUAN_MANUEL_CORREA:
      return "JUAN_MANUEL_CORREA";
    case DriverId.JORDAN_KING:
      return "JORDAN_KING";
    case DriverId.MAHAVEER_RAGHUNATHAN:
      return "MAHAVEER_RAGHUNATHAN";
    case DriverId.TATIANA_CALDERON:
      return "TATIANA_CALDERON";
    case DriverId.ANTHOINE_HUBERT:
      return "ANTHOINE_HUBERT";
    case DriverId.GUILIANO_ALESI:
      return "GUILIANO_ALESI";
    case DriverId.RALPH_BOSCHUNG:
      return "RALPH_BOSCHUNG";
    case DriverId.MICHAEL_SCHUMACHER:
      return "MICHAEL_SCHUMACHER";
    case DriverId.DAN_TICKTUM:
      return "DAN_TICKTUM";
    case DriverId.MARCUS_ARMSTRONG:
      return "MARCUS_ARMSTRONG";
    case DriverId.CHRISTIAN_LUNDGAARD:
      return "CHRISTIAN_LUNDGAARD";
    case DriverId.YUKI_TSUNODA:
      return "YUKI_TSUNODA";
    case DriverId.JEHAN_DARUVALA:
      return "JEHAN_DARUVALA";
    case DriverId.GULHERME_SAMAIA:
      return "GULHERME_SAMAIA";
    case DriverId.PEDRO_PIQUET:
      return "PEDRO_PIQUET";
    case DriverId.FELIPE_DRUGOVICH:
      return "FELIPE_DRUGOVICH";
    case DriverId.ROBERT_SCHWARTZMAN:
      return "ROBERT_SCHWARTZMAN";
    case DriverId.ROY_NISSANY:
      return "ROY_NISSANY";
    case DriverId.MARINO_SATO:
      return "MARINO_SATO";
    case DriverId.AIDAN_JACKSON:
      return "AIDAN_JACKSON";
    case DriverId.CASPER_AKKERMAN:
      return "CASPER_AKKERMAN";
    case DriverId.JENSON_BUTTON:
      return "JENSON_BUTTON";
    case DriverId.DAVID_COULTHARD:
      return "DAVID_COULTHARD";
    case DriverId.NICO_ROSBERG:
      return "NICO_ROSBERG";
    case DriverId.OSCAR_PIASTRI:
      return "OSCAR_PIASTRI";
    case DriverId.LIAM_LAWSON:
      return "LIAM_LAWSON";
    case DriverId.JURI_VIPS:
      return "JURI_VIPS";
    case DriverId.THEO_POURCHAIRE:
      return "THEO_POURCHAIRE";
    case DriverId.RICHARD_VERSCHOOR:
      return "RICHARD_VERSCHOOR";
    case DriverId.LIRIM_ZENDELI:
      return "LIRIM_ZENDELI";
    case DriverId.DAVID_BECKMANN:
      return "DAVID_BECKMANN";
    case DriverId.ALESSIO_DELEDDA:
      return "ALESSIO_DELEDDA";
    case DriverId.BENT_VISCAAL:
      return "BENT_VISCAAL";
    case DriverId.ENZO_FITTIPALDI:
      return "ENZO_FITTIPALDI";
    case DriverId.MARK_WEBBER:
      return "MARK_WEBBER";
    case DriverId.JACQUES_VILLENEUVE:
      return "JACQUES_VILLENEUVE";
    case DriverId.CALLIE_MAYER:
      return "CALLIE_MAYER";
    case DriverId.NOAH_BELL:
      return "NOAH_BELL";
    case DriverId.JAKE_HUGHES:
      return "JAKE_HUGHES";
    case DriverId.FREDERIK_VESTI:
      return "FREDERIK_VESTI";
    case DriverId.OLLI_CALDWELL:
      return "OLLI_CALDWELL";
    case DriverId.LOGAN_SARGEANT:
      return "LOGAN_SARGEANT";
    case DriverId.CEM_BOLUKBASI:
      return "CEM_BOLUKBASI";
    case DriverId.AYUMU_IWASA:
      return "AYUMU_IWASA";
    case DriverId.CLEMENT_NOVALAK:
      return "CLEMENT_NOVALAK";
    case DriverId.JACK_DOOHAN:
      return "JACK_DOOHAN";
    case DriverId.AMAURY_CORDEEL:
      return "AMAURY_CORDEEL";
    case DriverId.DENNIS_HAUGER:
      return "DENNIS_HAUGER";
    case DriverId.CALAN_WILLIAMS:
      return "CALAN_WILLIAMS";
    case DriverId.JAMIE_CHADWICK:
      return "JAMIE_CHADWICK";
    case DriverId.KAMUI_KOBAYASHI:
      return "KAMUI_KOBAYASHI";
    case DriverId.PASTOR_MALDONADO:
      return "PASTOR_MALDONADO";
    case DriverId.MIKA_HAKKINEN:
      return "MIKA_HAKKINEN";
    case DriverId.NIGEL_MANSELL:
      return "NIGEL_MANSELL";
    case DriverId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Team IDs */
export enum TeamId {
  TEAM_ID_UNKNOWN = 0,
  MERCEDES = 1,
  FERRARI = 2,
  RED_BULL_RACING = 3,
  WILLIAMS = 4,
  ASTON_MARTIN = 5,
  ALPINE = 6,
  ALPHA_TAURI = 7,
  HAAS = 8,
  MCLAREN = 9,
  ALFA_ROMEO = 10,
  MERCEDES_2020 = 86,
  FERRARI_2020 = 87,
  RED_BULL_2020 = 88,
  WILLIAMS_2020 = 89,
  RACING_POINT_2020 = 90,
  RENAULT_2020 = 91,
  ALPHA_TAURI_2020 = 92,
  HAAS_2020 = 93,
  MCLAREN_2020 = 94,
  ALFA_ROMEO_2020 = 95,
  ASTON_MARTIN_DB11_V12 = 96,
  ASTON_MARTIN_VANTAGE_F1_EDITION = 97,
  ASTON_MARTIN_VANTAGE_SAFETY_CAR = 98,
  FERRARI_F8_TRIBUTO = 99,
  FERRARI_ROMA = 100,
  MCLAREN_720S = 101,
  MCLAREN_ARTURA = 102,
  MERCEDES_AMG_GT_BLACK_SERIES_SAFETY_CAR = 103,
  MERCEDES_AMG_GTR_PRO = 104,
  F1_CUSTOM_TEAM = 105,
  PREMA_21 = 107,
  UNI_VIRTUOSI_21 = 108,
  CARLIN_21 = 109,
  HITECH_21 = 110,
  ART_GP_21 = 111,
  MP_MOTORSPORT_21 = 112,
  CHAROUZ_21 = 113,
  DAMS_21 = 114,
  CAMPOS_21 = 115,
  BWT_21 = 116,
  TRIDENT_21 = 117,
  MERCEDES_AMG_GT_BLACK_SERIES = 118,
  MERCEDES_22 = 119,
  FERRARI_22 = 120,
  RED_BULL_RACING_22 = 121,
  WILLIAMS_22 = 122,
  ASTON_MARTIN_22 = 123,
  ALPINE_22 = 124,
  ALPHA_TAURI_22 = 125,
  HAAS_22 = 126,
  MCLAREN_22 = 127,
  ALFA_ROMEO_22 = 128,
  KONNERSPORT_22 = 129,
  KONNERSPORT = 130,
  PREMA_22 = 131,
  VIRTUOSI_22 = 132,
  CARLIN_22 = 133,
  MP_MOTORSPORT_22 = 134,
  CHAROUZ_22 = 135,
  DAMS_22 = 136,
  CAMPOS_22 = 137,
  VAN_AMERSFOORT_RACING_22 = 138,
  TRIDENT_22 = 139,
  HITECH_22 = 140,
  ART_GP_22 = 141,
  UNRECOGNIZED = -1,
}

export function teamIdFromJSON(object: any): TeamId {
  switch (object) {
    case 0:
    case "TEAM_ID_UNKNOWN":
      return TeamId.TEAM_ID_UNKNOWN;
    case 1:
    case "MERCEDES":
      return TeamId.MERCEDES;
    case 2:
    case "FERRARI":
      return TeamId.FERRARI;
    case 3:
    case "RED_BULL_RACING":
      return TeamId.RED_BULL_RACING;
    case 4:
    case "WILLIAMS":
      return TeamId.WILLIAMS;
    case 5:
    case "ASTON_MARTIN":
      return TeamId.ASTON_MARTIN;
    case 6:
    case "ALPINE":
      return TeamId.ALPINE;
    case 7:
    case "ALPHA_TAURI":
      return TeamId.ALPHA_TAURI;
    case 8:
    case "HAAS":
      return TeamId.HAAS;
    case 9:
    case "MCLAREN":
      return TeamId.MCLAREN;
    case 10:
    case "ALFA_ROMEO":
      return TeamId.ALFA_ROMEO;
    case 86:
    case "MERCEDES_2020":
      return TeamId.MERCEDES_2020;
    case 87:
    case "FERRARI_2020":
      return TeamId.FERRARI_2020;
    case 88:
    case "RED_BULL_2020":
      return TeamId.RED_BULL_2020;
    case 89:
    case "WILLIAMS_2020":
      return TeamId.WILLIAMS_2020;
    case 90:
    case "RACING_POINT_2020":
      return TeamId.RACING_POINT_2020;
    case 91:
    case "RENAULT_2020":
      return TeamId.RENAULT_2020;
    case 92:
    case "ALPHA_TAURI_2020":
      return TeamId.ALPHA_TAURI_2020;
    case 93:
    case "HAAS_2020":
      return TeamId.HAAS_2020;
    case 94:
    case "MCLAREN_2020":
      return TeamId.MCLAREN_2020;
    case 95:
    case "ALFA_ROMEO_2020":
      return TeamId.ALFA_ROMEO_2020;
    case 96:
    case "ASTON_MARTIN_DB11_V12":
      return TeamId.ASTON_MARTIN_DB11_V12;
    case 97:
    case "ASTON_MARTIN_VANTAGE_F1_EDITION":
      return TeamId.ASTON_MARTIN_VANTAGE_F1_EDITION;
    case 98:
    case "ASTON_MARTIN_VANTAGE_SAFETY_CAR":
      return TeamId.ASTON_MARTIN_VANTAGE_SAFETY_CAR;
    case 99:
    case "FERRARI_F8_TRIBUTO":
      return TeamId.FERRARI_F8_TRIBUTO;
    case 100:
    case "FERRARI_ROMA":
      return TeamId.FERRARI_ROMA;
    case 101:
    case "MCLAREN_720S":
      return TeamId.MCLAREN_720S;
    case 102:
    case "MCLAREN_ARTURA":
      return TeamId.MCLAREN_ARTURA;
    case 103:
    case "MERCEDES_AMG_GT_BLACK_SERIES_SAFETY_CAR":
      return TeamId.MERCEDES_AMG_GT_BLACK_SERIES_SAFETY_CAR;
    case 104:
    case "MERCEDES_AMG_GTR_PRO":
      return TeamId.MERCEDES_AMG_GTR_PRO;
    case 105:
    case "F1_CUSTOM_TEAM":
      return TeamId.F1_CUSTOM_TEAM;
    case 107:
    case "PREMA_21":
      return TeamId.PREMA_21;
    case 108:
    case "UNI_VIRTUOSI_21":
      return TeamId.UNI_VIRTUOSI_21;
    case 109:
    case "CARLIN_21":
      return TeamId.CARLIN_21;
    case 110:
    case "HITECH_21":
      return TeamId.HITECH_21;
    case 111:
    case "ART_GP_21":
      return TeamId.ART_GP_21;
    case 112:
    case "MP_MOTORSPORT_21":
      return TeamId.MP_MOTORSPORT_21;
    case 113:
    case "CHAROUZ_21":
      return TeamId.CHAROUZ_21;
    case 114:
    case "DAMS_21":
      return TeamId.DAMS_21;
    case 115:
    case "CAMPOS_21":
      return TeamId.CAMPOS_21;
    case 116:
    case "BWT_21":
      return TeamId.BWT_21;
    case 117:
    case "TRIDENT_21":
      return TeamId.TRIDENT_21;
    case 118:
    case "MERCEDES_AMG_GT_BLACK_SERIES":
      return TeamId.MERCEDES_AMG_GT_BLACK_SERIES;
    case 119:
    case "MERCEDES_22":
      return TeamId.MERCEDES_22;
    case 120:
    case "FERRARI_22":
      return TeamId.FERRARI_22;
    case 121:
    case "RED_BULL_RACING_22":
      return TeamId.RED_BULL_RACING_22;
    case 122:
    case "WILLIAMS_22":
      return TeamId.WILLIAMS_22;
    case 123:
    case "ASTON_MARTIN_22":
      return TeamId.ASTON_MARTIN_22;
    case 124:
    case "ALPINE_22":
      return TeamId.ALPINE_22;
    case 125:
    case "ALPHA_TAURI_22":
      return TeamId.ALPHA_TAURI_22;
    case 126:
    case "HAAS_22":
      return TeamId.HAAS_22;
    case 127:
    case "MCLAREN_22":
      return TeamId.MCLAREN_22;
    case 128:
    case "ALFA_ROMEO_22":
      return TeamId.ALFA_ROMEO_22;
    case 129:
    case "KONNERSPORT_22":
      return TeamId.KONNERSPORT_22;
    case 130:
    case "KONNERSPORT":
      return TeamId.KONNERSPORT;
    case 131:
    case "PREMA_22":
      return TeamId.PREMA_22;
    case 132:
    case "VIRTUOSI_22":
      return TeamId.VIRTUOSI_22;
    case 133:
    case "CARLIN_22":
      return TeamId.CARLIN_22;
    case 134:
    case "MP_MOTORSPORT_22":
      return TeamId.MP_MOTORSPORT_22;
    case 135:
    case "CHAROUZ_22":
      return TeamId.CHAROUZ_22;
    case 136:
    case "DAMS_22":
      return TeamId.DAMS_22;
    case 137:
    case "CAMPOS_22":
      return TeamId.CAMPOS_22;
    case 138:
    case "VAN_AMERSFOORT_RACING_22":
      return TeamId.VAN_AMERSFOORT_RACING_22;
    case 139:
    case "TRIDENT_22":
      return TeamId.TRIDENT_22;
    case 140:
    case "HITECH_22":
      return TeamId.HITECH_22;
    case 141:
    case "ART_GP_22":
      return TeamId.ART_GP_22;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TeamId.UNRECOGNIZED;
  }
}

export function teamIdToJSON(object: TeamId): string {
  switch (object) {
    case TeamId.TEAM_ID_UNKNOWN:
      return "TEAM_ID_UNKNOWN";
    case TeamId.MERCEDES:
      return "MERCEDES";
    case TeamId.FERRARI:
      return "FERRARI";
    case TeamId.RED_BULL_RACING:
      return "RED_BULL_RACING";
    case TeamId.WILLIAMS:
      return "WILLIAMS";
    case TeamId.ASTON_MARTIN:
      return "ASTON_MARTIN";
    case TeamId.ALPINE:
      return "ALPINE";
    case TeamId.ALPHA_TAURI:
      return "ALPHA_TAURI";
    case TeamId.HAAS:
      return "HAAS";
    case TeamId.MCLAREN:
      return "MCLAREN";
    case TeamId.ALFA_ROMEO:
      return "ALFA_ROMEO";
    case TeamId.MERCEDES_2020:
      return "MERCEDES_2020";
    case TeamId.FERRARI_2020:
      return "FERRARI_2020";
    case TeamId.RED_BULL_2020:
      return "RED_BULL_2020";
    case TeamId.WILLIAMS_2020:
      return "WILLIAMS_2020";
    case TeamId.RACING_POINT_2020:
      return "RACING_POINT_2020";
    case TeamId.RENAULT_2020:
      return "RENAULT_2020";
    case TeamId.ALPHA_TAURI_2020:
      return "ALPHA_TAURI_2020";
    case TeamId.HAAS_2020:
      return "HAAS_2020";
    case TeamId.MCLAREN_2020:
      return "MCLAREN_2020";
    case TeamId.ALFA_ROMEO_2020:
      return "ALFA_ROMEO_2020";
    case TeamId.ASTON_MARTIN_DB11_V12:
      return "ASTON_MARTIN_DB11_V12";
    case TeamId.ASTON_MARTIN_VANTAGE_F1_EDITION:
      return "ASTON_MARTIN_VANTAGE_F1_EDITION";
    case TeamId.ASTON_MARTIN_VANTAGE_SAFETY_CAR:
      return "ASTON_MARTIN_VANTAGE_SAFETY_CAR";
    case TeamId.FERRARI_F8_TRIBUTO:
      return "FERRARI_F8_TRIBUTO";
    case TeamId.FERRARI_ROMA:
      return "FERRARI_ROMA";
    case TeamId.MCLAREN_720S:
      return "MCLAREN_720S";
    case TeamId.MCLAREN_ARTURA:
      return "MCLAREN_ARTURA";
    case TeamId.MERCEDES_AMG_GT_BLACK_SERIES_SAFETY_CAR:
      return "MERCEDES_AMG_GT_BLACK_SERIES_SAFETY_CAR";
    case TeamId.MERCEDES_AMG_GTR_PRO:
      return "MERCEDES_AMG_GTR_PRO";
    case TeamId.F1_CUSTOM_TEAM:
      return "F1_CUSTOM_TEAM";
    case TeamId.PREMA_21:
      return "PREMA_21";
    case TeamId.UNI_VIRTUOSI_21:
      return "UNI_VIRTUOSI_21";
    case TeamId.CARLIN_21:
      return "CARLIN_21";
    case TeamId.HITECH_21:
      return "HITECH_21";
    case TeamId.ART_GP_21:
      return "ART_GP_21";
    case TeamId.MP_MOTORSPORT_21:
      return "MP_MOTORSPORT_21";
    case TeamId.CHAROUZ_21:
      return "CHAROUZ_21";
    case TeamId.DAMS_21:
      return "DAMS_21";
    case TeamId.CAMPOS_21:
      return "CAMPOS_21";
    case TeamId.BWT_21:
      return "BWT_21";
    case TeamId.TRIDENT_21:
      return "TRIDENT_21";
    case TeamId.MERCEDES_AMG_GT_BLACK_SERIES:
      return "MERCEDES_AMG_GT_BLACK_SERIES";
    case TeamId.MERCEDES_22:
      return "MERCEDES_22";
    case TeamId.FERRARI_22:
      return "FERRARI_22";
    case TeamId.RED_BULL_RACING_22:
      return "RED_BULL_RACING_22";
    case TeamId.WILLIAMS_22:
      return "WILLIAMS_22";
    case TeamId.ASTON_MARTIN_22:
      return "ASTON_MARTIN_22";
    case TeamId.ALPINE_22:
      return "ALPINE_22";
    case TeamId.ALPHA_TAURI_22:
      return "ALPHA_TAURI_22";
    case TeamId.HAAS_22:
      return "HAAS_22";
    case TeamId.MCLAREN_22:
      return "MCLAREN_22";
    case TeamId.ALFA_ROMEO_22:
      return "ALFA_ROMEO_22";
    case TeamId.KONNERSPORT_22:
      return "KONNERSPORT_22";
    case TeamId.KONNERSPORT:
      return "KONNERSPORT";
    case TeamId.PREMA_22:
      return "PREMA_22";
    case TeamId.VIRTUOSI_22:
      return "VIRTUOSI_22";
    case TeamId.CARLIN_22:
      return "CARLIN_22";
    case TeamId.MP_MOTORSPORT_22:
      return "MP_MOTORSPORT_22";
    case TeamId.CHAROUZ_22:
      return "CHAROUZ_22";
    case TeamId.DAMS_22:
      return "DAMS_22";
    case TeamId.CAMPOS_22:
      return "CAMPOS_22";
    case TeamId.VAN_AMERSFOORT_RACING_22:
      return "VAN_AMERSFOORT_RACING_22";
    case TeamId.TRIDENT_22:
      return "TRIDENT_22";
    case TeamId.HITECH_22:
      return "HITECH_22";
    case TeamId.ART_GP_22:
      return "ART_GP_22";
    case TeamId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Nationality IDs */
export enum NationalityId {
  NATIONALITY_ID_UNKNOWN = 0,
  AMERICAN = 1,
  ARGENTINEAN = 2,
  AUSTRALIAN = 3,
  AUSTRIAN = 4,
  AZERBAIJANI = 5,
  BAHRAINI = 6,
  BELGIAN = 7,
  BOLIVIAN = 8,
  BRAZILIAN = 9,
  BRITISH = 10,
  BULGARIAN = 11,
  CAMEROONIAN = 12,
  CANADIAN = 13,
  CHILEAN = 14,
  CHINESE = 15,
  COLOMBIAN = 16,
  COSTA_RICAN = 17,
  CROATIAN = 18,
  CYPRIOT = 19,
  CZECH = 20,
  DANISH = 21,
  DUTCH = 22,
  ECUADORIAN = 23,
  ENGLISH = 24,
  EMIRIAN = 25,
  ESTONIAN = 26,
  FINNISH = 27,
  FRENCH = 28,
  GERMAN = 29,
  GHANAIAN = 30,
  GREEK = 31,
  GUATEMALAN = 32,
  HONDURAN = 33,
  HONG_KONGER = 34,
  HUNGARIAN = 35,
  ICELANDER = 36,
  INDIAN = 37,
  INDONESIAN = 38,
  IRISH = 39,
  ISRAELI = 40,
  ITALIAN = 41,
  JAMAICAN = 42,
  JAPANESE = 43,
  JORDANIAN = 44,
  KUWAITI = 45,
  LATVIAN = 46,
  LEBANESE = 47,
  LITHUANIAN = 48,
  LUXEMBOURGER = 49,
  MALAYSIAN = 50,
  MALTESE = 51,
  MEXICAN = 52,
  MONEGASQUE = 53,
  NEW_ZEALANDER = 54,
  NICARAGUAN = 55,
  NORTHERN_IRISH = 56,
  NORWEGIAN = 57,
  OMANI = 58,
  PAKISTANI = 59,
  PANAMANIAN = 60,
  PARAGUAYAN = 61,
  PERUVIAN = 62,
  POLISH = 63,
  PORTUGUESE = 64,
  QATARI = 65,
  ROMANIAN = 66,
  RUSSIAN = 67,
  SALVADORAN = 68,
  SAUDI = 69,
  SCOTTISH = 70,
  SERBIAN = 71,
  SINGAPOREAN = 72,
  SLOVAKIAN = 73,
  SLOVENIAN = 74,
  SOUTH_KOREAN = 75,
  SOUTH_AFRICAN = 76,
  SPANISH = 77,
  SWEDISH = 78,
  SWISS = 79,
  THAI = 80,
  TURKISH = 81,
  URUGUAYAN = 82,
  UKRAINIAN = 83,
  VENEZUELAN = 84,
  BARBADIAN = 85,
  WELSH = 86,
  VIETNAMESE = 87,
  UNRECOGNIZED = -1,
}

export function nationalityIdFromJSON(object: any): NationalityId {
  switch (object) {
    case 0:
    case "NATIONALITY_ID_UNKNOWN":
      return NationalityId.NATIONALITY_ID_UNKNOWN;
    case 1:
    case "AMERICAN":
      return NationalityId.AMERICAN;
    case 2:
    case "ARGENTINEAN":
      return NationalityId.ARGENTINEAN;
    case 3:
    case "AUSTRALIAN":
      return NationalityId.AUSTRALIAN;
    case 4:
    case "AUSTRIAN":
      return NationalityId.AUSTRIAN;
    case 5:
    case "AZERBAIJANI":
      return NationalityId.AZERBAIJANI;
    case 6:
    case "BAHRAINI":
      return NationalityId.BAHRAINI;
    case 7:
    case "BELGIAN":
      return NationalityId.BELGIAN;
    case 8:
    case "BOLIVIAN":
      return NationalityId.BOLIVIAN;
    case 9:
    case "BRAZILIAN":
      return NationalityId.BRAZILIAN;
    case 10:
    case "BRITISH":
      return NationalityId.BRITISH;
    case 11:
    case "BULGARIAN":
      return NationalityId.BULGARIAN;
    case 12:
    case "CAMEROONIAN":
      return NationalityId.CAMEROONIAN;
    case 13:
    case "CANADIAN":
      return NationalityId.CANADIAN;
    case 14:
    case "CHILEAN":
      return NationalityId.CHILEAN;
    case 15:
    case "CHINESE":
      return NationalityId.CHINESE;
    case 16:
    case "COLOMBIAN":
      return NationalityId.COLOMBIAN;
    case 17:
    case "COSTA_RICAN":
      return NationalityId.COSTA_RICAN;
    case 18:
    case "CROATIAN":
      return NationalityId.CROATIAN;
    case 19:
    case "CYPRIOT":
      return NationalityId.CYPRIOT;
    case 20:
    case "CZECH":
      return NationalityId.CZECH;
    case 21:
    case "DANISH":
      return NationalityId.DANISH;
    case 22:
    case "DUTCH":
      return NationalityId.DUTCH;
    case 23:
    case "ECUADORIAN":
      return NationalityId.ECUADORIAN;
    case 24:
    case "ENGLISH":
      return NationalityId.ENGLISH;
    case 25:
    case "EMIRIAN":
      return NationalityId.EMIRIAN;
    case 26:
    case "ESTONIAN":
      return NationalityId.ESTONIAN;
    case 27:
    case "FINNISH":
      return NationalityId.FINNISH;
    case 28:
    case "FRENCH":
      return NationalityId.FRENCH;
    case 29:
    case "GERMAN":
      return NationalityId.GERMAN;
    case 30:
    case "GHANAIAN":
      return NationalityId.GHANAIAN;
    case 31:
    case "GREEK":
      return NationalityId.GREEK;
    case 32:
    case "GUATEMALAN":
      return NationalityId.GUATEMALAN;
    case 33:
    case "HONDURAN":
      return NationalityId.HONDURAN;
    case 34:
    case "HONG_KONGER":
      return NationalityId.HONG_KONGER;
    case 35:
    case "HUNGARIAN":
      return NationalityId.HUNGARIAN;
    case 36:
    case "ICELANDER":
      return NationalityId.ICELANDER;
    case 37:
    case "INDIAN":
      return NationalityId.INDIAN;
    case 38:
    case "INDONESIAN":
      return NationalityId.INDONESIAN;
    case 39:
    case "IRISH":
      return NationalityId.IRISH;
    case 40:
    case "ISRAELI":
      return NationalityId.ISRAELI;
    case 41:
    case "ITALIAN":
      return NationalityId.ITALIAN;
    case 42:
    case "JAMAICAN":
      return NationalityId.JAMAICAN;
    case 43:
    case "JAPANESE":
      return NationalityId.JAPANESE;
    case 44:
    case "JORDANIAN":
      return NationalityId.JORDANIAN;
    case 45:
    case "KUWAITI":
      return NationalityId.KUWAITI;
    case 46:
    case "LATVIAN":
      return NationalityId.LATVIAN;
    case 47:
    case "LEBANESE":
      return NationalityId.LEBANESE;
    case 48:
    case "LITHUANIAN":
      return NationalityId.LITHUANIAN;
    case 49:
    case "LUXEMBOURGER":
      return NationalityId.LUXEMBOURGER;
    case 50:
    case "MALAYSIAN":
      return NationalityId.MALAYSIAN;
    case 51:
    case "MALTESE":
      return NationalityId.MALTESE;
    case 52:
    case "MEXICAN":
      return NationalityId.MEXICAN;
    case 53:
    case "MONEGASQUE":
      return NationalityId.MONEGASQUE;
    case 54:
    case "NEW_ZEALANDER":
      return NationalityId.NEW_ZEALANDER;
    case 55:
    case "NICARAGUAN":
      return NationalityId.NICARAGUAN;
    case 56:
    case "NORTHERN_IRISH":
      return NationalityId.NORTHERN_IRISH;
    case 57:
    case "NORWEGIAN":
      return NationalityId.NORWEGIAN;
    case 58:
    case "OMANI":
      return NationalityId.OMANI;
    case 59:
    case "PAKISTANI":
      return NationalityId.PAKISTANI;
    case 60:
    case "PANAMANIAN":
      return NationalityId.PANAMANIAN;
    case 61:
    case "PARAGUAYAN":
      return NationalityId.PARAGUAYAN;
    case 62:
    case "PERUVIAN":
      return NationalityId.PERUVIAN;
    case 63:
    case "POLISH":
      return NationalityId.POLISH;
    case 64:
    case "PORTUGUESE":
      return NationalityId.PORTUGUESE;
    case 65:
    case "QATARI":
      return NationalityId.QATARI;
    case 66:
    case "ROMANIAN":
      return NationalityId.ROMANIAN;
    case 67:
    case "RUSSIAN":
      return NationalityId.RUSSIAN;
    case 68:
    case "SALVADORAN":
      return NationalityId.SALVADORAN;
    case 69:
    case "SAUDI":
      return NationalityId.SAUDI;
    case 70:
    case "SCOTTISH":
      return NationalityId.SCOTTISH;
    case 71:
    case "SERBIAN":
      return NationalityId.SERBIAN;
    case 72:
    case "SINGAPOREAN":
      return NationalityId.SINGAPOREAN;
    case 73:
    case "SLOVAKIAN":
      return NationalityId.SLOVAKIAN;
    case 74:
    case "SLOVENIAN":
      return NationalityId.SLOVENIAN;
    case 75:
    case "SOUTH_KOREAN":
      return NationalityId.SOUTH_KOREAN;
    case 76:
    case "SOUTH_AFRICAN":
      return NationalityId.SOUTH_AFRICAN;
    case 77:
    case "SPANISH":
      return NationalityId.SPANISH;
    case 78:
    case "SWEDISH":
      return NationalityId.SWEDISH;
    case 79:
    case "SWISS":
      return NationalityId.SWISS;
    case 80:
    case "THAI":
      return NationalityId.THAI;
    case 81:
    case "TURKISH":
      return NationalityId.TURKISH;
    case 82:
    case "URUGUAYAN":
      return NationalityId.URUGUAYAN;
    case 83:
    case "UKRAINIAN":
      return NationalityId.UKRAINIAN;
    case 84:
    case "VENEZUELAN":
      return NationalityId.VENEZUELAN;
    case 85:
    case "BARBADIAN":
      return NationalityId.BARBADIAN;
    case 86:
    case "WELSH":
      return NationalityId.WELSH;
    case 87:
    case "VIETNAMESE":
      return NationalityId.VIETNAMESE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NationalityId.UNRECOGNIZED;
  }
}

export function nationalityIdToJSON(object: NationalityId): string {
  switch (object) {
    case NationalityId.NATIONALITY_ID_UNKNOWN:
      return "NATIONALITY_ID_UNKNOWN";
    case NationalityId.AMERICAN:
      return "AMERICAN";
    case NationalityId.ARGENTINEAN:
      return "ARGENTINEAN";
    case NationalityId.AUSTRALIAN:
      return "AUSTRALIAN";
    case NationalityId.AUSTRIAN:
      return "AUSTRIAN";
    case NationalityId.AZERBAIJANI:
      return "AZERBAIJANI";
    case NationalityId.BAHRAINI:
      return "BAHRAINI";
    case NationalityId.BELGIAN:
      return "BELGIAN";
    case NationalityId.BOLIVIAN:
      return "BOLIVIAN";
    case NationalityId.BRAZILIAN:
      return "BRAZILIAN";
    case NationalityId.BRITISH:
      return "BRITISH";
    case NationalityId.BULGARIAN:
      return "BULGARIAN";
    case NationalityId.CAMEROONIAN:
      return "CAMEROONIAN";
    case NationalityId.CANADIAN:
      return "CANADIAN";
    case NationalityId.CHILEAN:
      return "CHILEAN";
    case NationalityId.CHINESE:
      return "CHINESE";
    case NationalityId.COLOMBIAN:
      return "COLOMBIAN";
    case NationalityId.COSTA_RICAN:
      return "COSTA_RICAN";
    case NationalityId.CROATIAN:
      return "CROATIAN";
    case NationalityId.CYPRIOT:
      return "CYPRIOT";
    case NationalityId.CZECH:
      return "CZECH";
    case NationalityId.DANISH:
      return "DANISH";
    case NationalityId.DUTCH:
      return "DUTCH";
    case NationalityId.ECUADORIAN:
      return "ECUADORIAN";
    case NationalityId.ENGLISH:
      return "ENGLISH";
    case NationalityId.EMIRIAN:
      return "EMIRIAN";
    case NationalityId.ESTONIAN:
      return "ESTONIAN";
    case NationalityId.FINNISH:
      return "FINNISH";
    case NationalityId.FRENCH:
      return "FRENCH";
    case NationalityId.GERMAN:
      return "GERMAN";
    case NationalityId.GHANAIAN:
      return "GHANAIAN";
    case NationalityId.GREEK:
      return "GREEK";
    case NationalityId.GUATEMALAN:
      return "GUATEMALAN";
    case NationalityId.HONDURAN:
      return "HONDURAN";
    case NationalityId.HONG_KONGER:
      return "HONG_KONGER";
    case NationalityId.HUNGARIAN:
      return "HUNGARIAN";
    case NationalityId.ICELANDER:
      return "ICELANDER";
    case NationalityId.INDIAN:
      return "INDIAN";
    case NationalityId.INDONESIAN:
      return "INDONESIAN";
    case NationalityId.IRISH:
      return "IRISH";
    case NationalityId.ISRAELI:
      return "ISRAELI";
    case NationalityId.ITALIAN:
      return "ITALIAN";
    case NationalityId.JAMAICAN:
      return "JAMAICAN";
    case NationalityId.JAPANESE:
      return "JAPANESE";
    case NationalityId.JORDANIAN:
      return "JORDANIAN";
    case NationalityId.KUWAITI:
      return "KUWAITI";
    case NationalityId.LATVIAN:
      return "LATVIAN";
    case NationalityId.LEBANESE:
      return "LEBANESE";
    case NationalityId.LITHUANIAN:
      return "LITHUANIAN";
    case NationalityId.LUXEMBOURGER:
      return "LUXEMBOURGER";
    case NationalityId.MALAYSIAN:
      return "MALAYSIAN";
    case NationalityId.MALTESE:
      return "MALTESE";
    case NationalityId.MEXICAN:
      return "MEXICAN";
    case NationalityId.MONEGASQUE:
      return "MONEGASQUE";
    case NationalityId.NEW_ZEALANDER:
      return "NEW_ZEALANDER";
    case NationalityId.NICARAGUAN:
      return "NICARAGUAN";
    case NationalityId.NORTHERN_IRISH:
      return "NORTHERN_IRISH";
    case NationalityId.NORWEGIAN:
      return "NORWEGIAN";
    case NationalityId.OMANI:
      return "OMANI";
    case NationalityId.PAKISTANI:
      return "PAKISTANI";
    case NationalityId.PANAMANIAN:
      return "PANAMANIAN";
    case NationalityId.PARAGUAYAN:
      return "PARAGUAYAN";
    case NationalityId.PERUVIAN:
      return "PERUVIAN";
    case NationalityId.POLISH:
      return "POLISH";
    case NationalityId.PORTUGUESE:
      return "PORTUGUESE";
    case NationalityId.QATARI:
      return "QATARI";
    case NationalityId.ROMANIAN:
      return "ROMANIAN";
    case NationalityId.RUSSIAN:
      return "RUSSIAN";
    case NationalityId.SALVADORAN:
      return "SALVADORAN";
    case NationalityId.SAUDI:
      return "SAUDI";
    case NationalityId.SCOTTISH:
      return "SCOTTISH";
    case NationalityId.SERBIAN:
      return "SERBIAN";
    case NationalityId.SINGAPOREAN:
      return "SINGAPOREAN";
    case NationalityId.SLOVAKIAN:
      return "SLOVAKIAN";
    case NationalityId.SLOVENIAN:
      return "SLOVENIAN";
    case NationalityId.SOUTH_KOREAN:
      return "SOUTH_KOREAN";
    case NationalityId.SOUTH_AFRICAN:
      return "SOUTH_AFRICAN";
    case NationalityId.SPANISH:
      return "SPANISH";
    case NationalityId.SWEDISH:
      return "SWEDISH";
    case NationalityId.SWISS:
      return "SWISS";
    case NationalityId.THAI:
      return "THAI";
    case NationalityId.TURKISH:
      return "TURKISH";
    case NationalityId.URUGUAYAN:
      return "URUGUAYAN";
    case NationalityId.UKRAINIAN:
      return "UKRAINIAN";
    case NationalityId.VENEZUELAN:
      return "VENEZUELAN";
    case NationalityId.BARBADIAN:
      return "BARBADIAN";
    case NationalityId.WELSH:
      return "WELSH";
    case NationalityId.VIETNAMESE:
      return "VIETNAMESE";
    case NationalityId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Surface types */
export enum SurfaceType {
  SURFACE_TYPE_TARMAC = 0,
  RUMBLE_STRIP = 1,
  CONCRETE = 2,
  ROCK = 3,
  GRAVEL = 4,
  MUD = 5,
  SAND = 6,
  GRASS = 7,
  WATER = 8,
  COBBLESTONE = 9,
  METAL = 10,
  RIDGED = 11,
  UNRECOGNIZED = -1,
}

export function surfaceTypeFromJSON(object: any): SurfaceType {
  switch (object) {
    case 0:
    case "SURFACE_TYPE_TARMAC":
      return SurfaceType.SURFACE_TYPE_TARMAC;
    case 1:
    case "RUMBLE_STRIP":
      return SurfaceType.RUMBLE_STRIP;
    case 2:
    case "CONCRETE":
      return SurfaceType.CONCRETE;
    case 3:
    case "ROCK":
      return SurfaceType.ROCK;
    case 4:
    case "GRAVEL":
      return SurfaceType.GRAVEL;
    case 5:
    case "MUD":
      return SurfaceType.MUD;
    case 6:
    case "SAND":
      return SurfaceType.SAND;
    case 7:
    case "GRASS":
      return SurfaceType.GRASS;
    case 8:
    case "WATER":
      return SurfaceType.WATER;
    case 9:
    case "COBBLESTONE":
      return SurfaceType.COBBLESTONE;
    case 10:
    case "METAL":
      return SurfaceType.METAL;
    case 11:
    case "RIDGED":
      return SurfaceType.RIDGED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SurfaceType.UNRECOGNIZED;
  }
}

export function surfaceTypeToJSON(object: SurfaceType): string {
  switch (object) {
    case SurfaceType.SURFACE_TYPE_TARMAC:
      return "SURFACE_TYPE_TARMAC";
    case SurfaceType.RUMBLE_STRIP:
      return "RUMBLE_STRIP";
    case SurfaceType.CONCRETE:
      return "CONCRETE";
    case SurfaceType.ROCK:
      return "ROCK";
    case SurfaceType.GRAVEL:
      return "GRAVEL";
    case SurfaceType.MUD:
      return "MUD";
    case SurfaceType.SAND:
      return "SAND";
    case SurfaceType.GRASS:
      return "GRASS";
    case SurfaceType.WATER:
      return "WATER";
    case SurfaceType.COBBLESTONE:
      return "COBBLESTONE";
    case SurfaceType.METAL:
      return "METAL";
    case SurfaceType.RIDGED:
      return "RIDGED";
    case SurfaceType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Pit limiter status */
export enum PitLimiterStatus {
  PIT_LIMITER_OFF = 0,
  PIT_LIMITER_ON = 1,
  UNRECOGNIZED = -1,
}

export function pitLimiterStatusFromJSON(object: any): PitLimiterStatus {
  switch (object) {
    case 0:
    case "PIT_LIMITER_OFF":
      return PitLimiterStatus.PIT_LIMITER_OFF;
    case 1:
    case "PIT_LIMITER_ON":
      return PitLimiterStatus.PIT_LIMITER_ON;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PitLimiterStatus.UNRECOGNIZED;
  }
}

export function pitLimiterStatusToJSON(object: PitLimiterStatus): string {
  switch (object) {
    case PitLimiterStatus.PIT_LIMITER_OFF:
      return "PIT_LIMITER_OFF";
    case PitLimiterStatus.PIT_LIMITER_ON:
      return "PIT_LIMITER_ON";
    case PitLimiterStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** DRS allowed status */
export enum DrsAllowedStatus {
  DRS_UNKNOWN = 0,
  DRS_NOT_ALLOWED = 1,
  DRS_ALLOWED = 2,
  UNRECOGNIZED = -1,
}

export function drsAllowedStatusFromJSON(object: any): DrsAllowedStatus {
  switch (object) {
    case 0:
    case "DRS_UNKNOWN":
      return DrsAllowedStatus.DRS_UNKNOWN;
    case 1:
    case "DRS_NOT_ALLOWED":
      return DrsAllowedStatus.DRS_NOT_ALLOWED;
    case 2:
    case "DRS_ALLOWED":
      return DrsAllowedStatus.DRS_ALLOWED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DrsAllowedStatus.UNRECOGNIZED;
  }
}

export function drsAllowedStatusToJSON(object: DrsAllowedStatus): string {
  switch (object) {
    case DrsAllowedStatus.DRS_UNKNOWN:
      return "DRS_UNKNOWN";
    case DrsAllowedStatus.DRS_NOT_ALLOWED:
      return "DRS_NOT_ALLOWED";
    case DrsAllowedStatus.DRS_ALLOWED:
      return "DRS_ALLOWED";
    case DrsAllowedStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Actual tyre compound */
export enum ActualTyreCompound {
  ACTUAL_TYRE_COMPOUND_UNKNOWN = 0,
  INTER = 7,
  WET = 8,
  C5 = 16,
  C4 = 17,
  C3 = 18,
  C2 = 19,
  C1 = 20,
  C0 = 21,
  UNRECOGNIZED = -1,
}

export function actualTyreCompoundFromJSON(object: any): ActualTyreCompound {
  switch (object) {
    case 0:
    case "ACTUAL_TYRE_COMPOUND_UNKNOWN":
      return ActualTyreCompound.ACTUAL_TYRE_COMPOUND_UNKNOWN;
    case 7:
    case "INTER":
      return ActualTyreCompound.INTER;
    case 8:
    case "WET":
      return ActualTyreCompound.WET;
    case 16:
    case "C5":
      return ActualTyreCompound.C5;
    case 17:
    case "C4":
      return ActualTyreCompound.C4;
    case 18:
    case "C3":
      return ActualTyreCompound.C3;
    case 19:
    case "C2":
      return ActualTyreCompound.C2;
    case 20:
    case "C1":
      return ActualTyreCompound.C1;
    case 21:
    case "C0":
      return ActualTyreCompound.C0;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ActualTyreCompound.UNRECOGNIZED;
  }
}

export function actualTyreCompoundToJSON(object: ActualTyreCompound): string {
  switch (object) {
    case ActualTyreCompound.ACTUAL_TYRE_COMPOUND_UNKNOWN:
      return "ACTUAL_TYRE_COMPOUND_UNKNOWN";
    case ActualTyreCompound.INTER:
      return "INTER";
    case ActualTyreCompound.WET:
      return "WET";
    case ActualTyreCompound.C5:
      return "C5";
    case ActualTyreCompound.C4:
      return "C4";
    case ActualTyreCompound.C3:
      return "C3";
    case ActualTyreCompound.C2:
      return "C2";
    case ActualTyreCompound.C1:
      return "C1";
    case ActualTyreCompound.C0:
      return "C0";
    case ActualTyreCompound.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Visual tyre compound */
export enum VisualTyreCompound {
  VISUAL_TYRE_COMPOUND_UNKNOWN = 0,
  VISUAL_INTER = 7,
  VISUAL_WET = 8,
  SOFT = 16,
  MEDIUM = 17,
  HARD = 18,
  UNRECOGNIZED = -1,
}

export function visualTyreCompoundFromJSON(object: any): VisualTyreCompound {
  switch (object) {
    case 0:
    case "VISUAL_TYRE_COMPOUND_UNKNOWN":
      return VisualTyreCompound.VISUAL_TYRE_COMPOUND_UNKNOWN;
    case 7:
    case "VISUAL_INTER":
      return VisualTyreCompound.VISUAL_INTER;
    case 8:
    case "VISUAL_WET":
      return VisualTyreCompound.VISUAL_WET;
    case 16:
    case "SOFT":
      return VisualTyreCompound.SOFT;
    case 17:
    case "MEDIUM":
      return VisualTyreCompound.MEDIUM;
    case 18:
    case "HARD":
      return VisualTyreCompound.HARD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VisualTyreCompound.UNRECOGNIZED;
  }
}

export function visualTyreCompoundToJSON(object: VisualTyreCompound): string {
  switch (object) {
    case VisualTyreCompound.VISUAL_TYRE_COMPOUND_UNKNOWN:
      return "VISUAL_TYRE_COMPOUND_UNKNOWN";
    case VisualTyreCompound.VISUAL_INTER:
      return "VISUAL_INTER";
    case VisualTyreCompound.VISUAL_WET:
      return "VISUAL_WET";
    case VisualTyreCompound.SOFT:
      return "SOFT";
    case VisualTyreCompound.MEDIUM:
      return "MEDIUM";
    case VisualTyreCompound.HARD:
      return "HARD";
    case VisualTyreCompound.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Vehicle FIA flags */
export enum VehicleFiaFlag {
  FIA_FLAG_INVALID = 0,
  FIA_FLAG_NONE = 1,
  FIA_FLAG_GREEN = 2,
  FIA_FLAG_BLUE = 3,
  FIA_FLAG_YELLOW = 4,
  UNRECOGNIZED = -1,
}

export function vehicleFiaFlagFromJSON(object: any): VehicleFiaFlag {
  switch (object) {
    case 0:
    case "FIA_FLAG_INVALID":
      return VehicleFiaFlag.FIA_FLAG_INVALID;
    case 1:
    case "FIA_FLAG_NONE":
      return VehicleFiaFlag.FIA_FLAG_NONE;
    case 2:
    case "FIA_FLAG_GREEN":
      return VehicleFiaFlag.FIA_FLAG_GREEN;
    case 3:
    case "FIA_FLAG_BLUE":
      return VehicleFiaFlag.FIA_FLAG_BLUE;
    case 4:
    case "FIA_FLAG_YELLOW":
      return VehicleFiaFlag.FIA_FLAG_YELLOW;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VehicleFiaFlag.UNRECOGNIZED;
  }
}

export function vehicleFiaFlagToJSON(object: VehicleFiaFlag): string {
  switch (object) {
    case VehicleFiaFlag.FIA_FLAG_INVALID:
      return "FIA_FLAG_INVALID";
    case VehicleFiaFlag.FIA_FLAG_NONE:
      return "FIA_FLAG_NONE";
    case VehicleFiaFlag.FIA_FLAG_GREEN:
      return "FIA_FLAG_GREEN";
    case VehicleFiaFlag.FIA_FLAG_BLUE:
      return "FIA_FLAG_BLUE";
    case VehicleFiaFlag.FIA_FLAG_YELLOW:
      return "FIA_FLAG_YELLOW";
    case VehicleFiaFlag.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ERS deploy mode */
export enum ErsDeployMode {
  ERS_NONE = 0,
  ERS_MEDIUM = 1,
  ERS_HOTLAP = 2,
  ERS_OVERTAKE = 3,
  UNRECOGNIZED = -1,
}

export function ersDeployModeFromJSON(object: any): ErsDeployMode {
  switch (object) {
    case 0:
    case "ERS_NONE":
      return ErsDeployMode.ERS_NONE;
    case 1:
    case "ERS_MEDIUM":
      return ErsDeployMode.ERS_MEDIUM;
    case 2:
    case "ERS_HOTLAP":
      return ErsDeployMode.ERS_HOTLAP;
    case 3:
    case "ERS_OVERTAKE":
      return ErsDeployMode.ERS_OVERTAKE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ErsDeployMode.UNRECOGNIZED;
  }
}

export function ersDeployModeToJSON(object: ErsDeployMode): string {
  switch (object) {
    case ErsDeployMode.ERS_NONE:
      return "ERS_NONE";
    case ErsDeployMode.ERS_MEDIUM:
      return "ERS_MEDIUM";
    case ErsDeployMode.ERS_HOTLAP:
      return "ERS_HOTLAP";
    case ErsDeployMode.ERS_OVERTAKE:
      return "ERS_OVERTAKE";
    case ErsDeployMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Network paused status */
export enum NetworkPausedStatus {
  NOT_PAUSED = 0,
  PAUSED = 1,
  UNRECOGNIZED = -1,
}

export function networkPausedStatusFromJSON(object: any): NetworkPausedStatus {
  switch (object) {
    case 0:
    case "NOT_PAUSED":
      return NetworkPausedStatus.NOT_PAUSED;
    case 1:
    case "PAUSED":
      return NetworkPausedStatus.PAUSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NetworkPausedStatus.UNRECOGNIZED;
  }
}

export function networkPausedStatusToJSON(object: NetworkPausedStatus): string {
  switch (object) {
    case NetworkPausedStatus.NOT_PAUSED:
      return "NOT_PAUSED";
    case NetworkPausedStatus.PAUSED:
      return "PAUSED";
    case NetworkPausedStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
