from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PacketType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PACKET_TYPE_UNSPECIFIED: _ClassVar[PacketType]
    PACKET_MOTION_DATA: _ClassVar[PacketType]
    PACKET_SESSION_DATA: _ClassVar[PacketType]
    PACKET_LAP_DATA: _ClassVar[PacketType]
    PACKET_EVENT_DATA: _ClassVar[PacketType]
    PACKET_PARTICIPANTS_DATA: _ClassVar[PacketType]
    PACKET_CAR_SETUP_DATA: _ClassVar[PacketType]
    PACKET_CAR_TELEMETRY_DATA: _ClassVar[PacketType]
    PACKET_CAR_STATUS_DATA: _ClassVar[PacketType]
    PACKET_FINAL_CLASSIFICATION_DATA: _ClassVar[PacketType]
    PACKET_LOBBY_INFO_DATA: _ClassVar[PacketType]
    PACKET_CAR_DAMAGE_DATA: _ClassVar[PacketType]
    PACKET_SESSION_HISTORY_DATA: _ClassVar[PacketType]
    PACKET_TYRE_SETS_DATA: _ClassVar[PacketType]
    PACKET_MOTION_EX_DATA: _ClassVar[PacketType]

class Weather(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    WEATHER_UNSPECIFIED: _ClassVar[Weather]
    CLEAR: _ClassVar[Weather]
    LIGHT_CLOUD: _ClassVar[Weather]
    OVERCAST: _ClassVar[Weather]
    LIGHT_RAIN: _ClassVar[Weather]
    HEAVY_RAIN: _ClassVar[Weather]
    STORM: _ClassVar[Weather]

class SessionType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SESSION_TYPE_UNKNOWN: _ClassVar[SessionType]
    P1: _ClassVar[SessionType]
    P2: _ClassVar[SessionType]
    P3: _ClassVar[SessionType]
    SHORT_P: _ClassVar[SessionType]
    Q1: _ClassVar[SessionType]
    Q2: _ClassVar[SessionType]
    Q3: _ClassVar[SessionType]
    SHORT_Q: _ClassVar[SessionType]
    OSQ: _ClassVar[SessionType]
    R: _ClassVar[SessionType]
    R2: _ClassVar[SessionType]
    R3: _ClassVar[SessionType]
    TIME_TRIAL: _ClassVar[SessionType]

class TrackId(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    TRACK_ID_UNKNOWN: _ClassVar[TrackId]
    MELBOURNE: _ClassVar[TrackId]
    PAUL_RICARD: _ClassVar[TrackId]
    SHANGHAI: _ClassVar[TrackId]
    SAKHIR_BAHRAIN: _ClassVar[TrackId]
    CATALUNYA: _ClassVar[TrackId]
    MONACO: _ClassVar[TrackId]
    MONTREAL: _ClassVar[TrackId]
    SILVERSTONE: _ClassVar[TrackId]
    HOCKENHEIM: _ClassVar[TrackId]
    HUNGARORING: _ClassVar[TrackId]
    SPA: _ClassVar[TrackId]
    MONZA: _ClassVar[TrackId]
    SINGAPORE: _ClassVar[TrackId]
    SUZUKA: _ClassVar[TrackId]
    ABU_DHABI: _ClassVar[TrackId]
    TEXAS: _ClassVar[TrackId]
    BRAZIL: _ClassVar[TrackId]
    AUSTRIA: _ClassVar[TrackId]
    SOCHI: _ClassVar[TrackId]
    MEXICO: _ClassVar[TrackId]
    BAKU_AZERBAIJAN: _ClassVar[TrackId]
    SAKHIR_SHORT: _ClassVar[TrackId]
    SILVERSTONE_SHORT: _ClassVar[TrackId]
    TEXAS_SHORT: _ClassVar[TrackId]
    SUZUKA_SHORT: _ClassVar[TrackId]
    HANOI: _ClassVar[TrackId]
    ZANDVOORT: _ClassVar[TrackId]
    IMOLA: _ClassVar[TrackId]
    PORTIMAO: _ClassVar[TrackId]
    JEDDAH: _ClassVar[TrackId]
    MIAMI: _ClassVar[TrackId]
    LAS_VEGAS: _ClassVar[TrackId]
    LOSAIL: _ClassVar[TrackId]

class TemperatureChange(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    TEMPERATURE_CHANGE_UNSPECIFIED: _ClassVar[TemperatureChange]
    UP: _ClassVar[TemperatureChange]
    DOWN: _ClassVar[TemperatureChange]
    NO_CHANGE: _ClassVar[TemperatureChange]

class SafetyCarStatus(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SAFETY_CAR_STATUS_UNSPECIFIED: _ClassVar[SafetyCarStatus]
    NO_SAFETY_CAR: _ClassVar[SafetyCarStatus]
    FULL_SAFETY_CAR: _ClassVar[SafetyCarStatus]
    VIRTUAL_SAFETY_CAR: _ClassVar[SafetyCarStatus]
    FORMATION_LAP: _ClassVar[SafetyCarStatus]

class PitStatus(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PIT_STATUS_NONE: _ClassVar[PitStatus]
    PITTING: _ClassVar[PitStatus]
    IN_PIT_AREA: _ClassVar[PitStatus]

class Sector(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SECTOR_UNSPECIFIED: _ClassVar[Sector]
    SECTOR1: _ClassVar[Sector]
    SECTOR2: _ClassVar[Sector]
    SECTOR3: _ClassVar[Sector]

class LapValidity(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    VALID: _ClassVar[LapValidity]
    INVALID: _ClassVar[LapValidity]

class ResultStatus(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    RESULT_STATUS_INVALID: _ClassVar[ResultStatus]
    INACTIVE: _ClassVar[ResultStatus]
    ACTIVE: _ClassVar[ResultStatus]
    FINISHED: _ClassVar[ResultStatus]
    DNF: _ClassVar[ResultStatus]
    DSQ: _ClassVar[ResultStatus]
    NOT_CLASSIFIED: _ClassVar[ResultStatus]
    RETIRED: _ClassVar[ResultStatus]

class PitStopShouldServePenalty(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NO: _ClassVar[PitStopShouldServePenalty]
    YES: _ClassVar[PitStopShouldServePenalty]

class EventType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    EVENT_TYPE_UNSPECIFIED: _ClassVar[EventType]
    SESSION_STARTED: _ClassVar[EventType]
    SESSION_ENDED: _ClassVar[EventType]
    FASTEST_LAP: _ClassVar[EventType]
    RETIREMENT: _ClassVar[EventType]
    DRS_ENABLED: _ClassVar[EventType]
    DRS_DISABLED: _ClassVar[EventType]
    TEAM_MATE_IN_PITS: _ClassVar[EventType]
    CHEQUERED_FLAG: _ClassVar[EventType]
    RACE_WINNER: _ClassVar[EventType]
    PENALTY_ISSUED: _ClassVar[EventType]
    SPEED_TRAP_TRIGGERED: _ClassVar[EventType]
    START_LIGHT: _ClassVar[EventType]
    LIGHTS_OUT: _ClassVar[EventType]
    DRIVE_THROUGH_SERVED: _ClassVar[EventType]
    STOP_GO_SERVED: _ClassVar[EventType]
    FLASHBACK: _ClassVar[EventType]
    BUTTON_STATUS: _ClassVar[EventType]
    RED_FLAG: _ClassVar[EventType]
    OVERTAKE: _ClassVar[EventType]
    UNKNOWN: _ClassVar[EventType]

class PenaltyType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PENALTY_TYPE_UNSPECIFIED: _ClassVar[PenaltyType]
    DRIVE_THROUGH: _ClassVar[PenaltyType]
    STOP_GO: _ClassVar[PenaltyType]
    GRID_PENALTY: _ClassVar[PenaltyType]
    PENALTY_REMINDER: _ClassVar[PenaltyType]
    TIME_PENALTY: _ClassVar[PenaltyType]
    WARNING: _ClassVar[PenaltyType]
    DISQUALIFIED: _ClassVar[PenaltyType]
    REMOVED_FROM_FORMATION_LAP: _ClassVar[PenaltyType]
    PARKED_TOO_LONG_TIMER: _ClassVar[PenaltyType]
    TYRE_REGULATIONS: _ClassVar[PenaltyType]
    THIS_LAP_INVALIDATED: _ClassVar[PenaltyType]
    THIS_AND_NEXT_LAP_INVALIDATED: _ClassVar[PenaltyType]
    THIS_LAP_INVALIDATED_WITHOUT_REASON: _ClassVar[PenaltyType]
    THIS_AND_NEXT_LAP_INVALIDATED_WITHOUT_REASON: _ClassVar[PenaltyType]
    THIS_AND_PREVIOUS_LAP_INVALIDATED: _ClassVar[PenaltyType]
    THIS_AND_PREVIOUS_LAP_INVALIDATED_WITHOUT_REASON: _ClassVar[PenaltyType]
    RETIRED_PENALTY: _ClassVar[PenaltyType]
    BLACK_FLAG_TIMER: _ClassVar[PenaltyType]

class InfringementType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    INFRINGEMENT_TYPE_UNSPECIFIED: _ClassVar[InfringementType]
    BLOCKING_BY_SLOW_DRIVING: _ClassVar[InfringementType]
    BLOCKING_BY_WRONG_WAY_DRIVING: _ClassVar[InfringementType]
    REVERSING_OFF_THE_START_LINE: _ClassVar[InfringementType]
    BIG_COLLISION: _ClassVar[InfringementType]
    SMALL_COLLISION: _ClassVar[InfringementType]
    COLLISION_FAILED_TO_HAND_BACK_POSITION_SINGLE: _ClassVar[InfringementType]
    COLLISION_FAILED_TO_HAND_BACK_POSITION_MULTIPLE: _ClassVar[InfringementType]
    CORNER_CUTTING_GAINED_TIME: _ClassVar[InfringementType]
    CORNER_CUTTING_OVERTAKE_SINGLE: _ClassVar[InfringementType]
    CORNER_CUTTING_OVERTAKE_MULTIPLE: _ClassVar[InfringementType]
    CROSSED_PIT_EXIT_LANE: _ClassVar[InfringementType]
    IGNORING_BLUE_FLAGS: _ClassVar[InfringementType]
    IGNORING_YELLOW_FLAGS: _ClassVar[InfringementType]
    IGNORING_DRIVE_THROUGH: _ClassVar[InfringementType]
    TOO_MANY_DRIVE_THROUGHS: _ClassVar[InfringementType]
    DRIVE_THROUGH_REMINDER_SERVE_WITHIN_N_LAPS: _ClassVar[InfringementType]
    DRIVE_THROUGH_REMINDER_SERVE_THIS_LAP: _ClassVar[InfringementType]
    PIT_LANE_SPEEDING: _ClassVar[InfringementType]
    PARKED_FOR_TOO_LONG: _ClassVar[InfringementType]
    IGNORING_TYRE_REGULATIONS: _ClassVar[InfringementType]
    TOO_MANY_PENALTIES: _ClassVar[InfringementType]
    MULTIPLE_WARNINGS: _ClassVar[InfringementType]
    APPROACHING_DISQUALIFICATION: _ClassVar[InfringementType]
    TYRE_REGULATIONS_SELECT_SINGLE: _ClassVar[InfringementType]
    TYRE_REGULATIONS_SELECT_MULTIPLE: _ClassVar[InfringementType]
    LAP_INVALIDATED_CORNER_CUTTING: _ClassVar[InfringementType]
    LAP_INVALIDATED_RUNNING_WIDE: _ClassVar[InfringementType]
    CORNER_CUTTING_RAN_WIDE_GAINED_TIME_MINOR: _ClassVar[InfringementType]
    CORNER_CUTTING_RAN_WIDE_GAINED_TIME_SIGNIFICANT: _ClassVar[InfringementType]
    CORNER_CUTTING_RAN_WIDE_GAINED_TIME_EXTREME: _ClassVar[InfringementType]
    LAP_INVALIDATED_WALL_RIDING: _ClassVar[InfringementType]
    LAP_INVALIDATED_FLASHBACK_USED: _ClassVar[InfringementType]
    LAP_INVALIDATED_RESET_TO_TRACK: _ClassVar[InfringementType]
    BLOCKING_THE_PITLANE: _ClassVar[InfringementType]
    JUMP_START: _ClassVar[InfringementType]
    SAFETY_CAR_TO_CAR_COLLISION: _ClassVar[InfringementType]
    SAFETY_CAR_ILLEGAL_OVERTAKE: _ClassVar[InfringementType]
    SAFETY_CAR_EXCEEDING_ALLOWED_PACE: _ClassVar[InfringementType]
    VIRTUAL_SAFETY_CAR_EXCEEDING_ALLOWED_PACE: _ClassVar[InfringementType]
    FORMATION_LAP_BELOW_ALLOWED_SPEED: _ClassVar[InfringementType]
    FORMATION_LAP_PARKING: _ClassVar[InfringementType]
    RETIRED_MECHANICAL_FAILURE: _ClassVar[InfringementType]
    RETIRED_TERMINALLY_DAMAGED: _ClassVar[InfringementType]
    SAFETY_CAR_FALLING_TOO_FAR_BACK: _ClassVar[InfringementType]
    BLACK_FLAG_TIMER_INFRINGEMENT: _ClassVar[InfringementType]
    UNSERVED_STOP_GO_PENALTY: _ClassVar[InfringementType]
    UNSERVED_DRIVE_THROUGH_PENALTY: _ClassVar[InfringementType]
    ENGINE_COMPONENT_CHANGE: _ClassVar[InfringementType]
    GEARBOX_CHANGE: _ClassVar[InfringementType]
    PARC_FERME_CHANGE: _ClassVar[InfringementType]
    LEAGUE_GRID_PENALTY: _ClassVar[InfringementType]
    RETRY_PENALTY: _ClassVar[InfringementType]
    ILLEGAL_TIME_GAIN: _ClassVar[InfringementType]
    MANDATORY_PITSTOP: _ClassVar[InfringementType]
    ATTRIBUTE_ASSIGNED: _ClassVar[InfringementType]

class DriverId(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    DRIVER_ID_UNKNOWN: _ClassVar[DriverId]
    CARLOS_SAINZ: _ClassVar[DriverId]
    DANIIL_KVYAT: _ClassVar[DriverId]
    DANIEL_RICCIARDO: _ClassVar[DriverId]
    FERNANDO_ALONSO: _ClassVar[DriverId]
    FELIPE_MASSA: _ClassVar[DriverId]
    KIMI_RAIKKONEN: _ClassVar[DriverId]
    LEWIS_HAMILTON: _ClassVar[DriverId]
    MAX_VERSTAPPEN: _ClassVar[DriverId]
    NICO_HULKENBURG: _ClassVar[DriverId]
    KEVIN_MAGNUSSEN: _ClassVar[DriverId]
    ROMAIN_GROSJEAN: _ClassVar[DriverId]
    SEBASTIAN_VETTEL: _ClassVar[DriverId]
    SERGIO_PEREZ: _ClassVar[DriverId]
    VALTTERI_BOTTAS: _ClassVar[DriverId]
    ESTEBAN_OCON: _ClassVar[DriverId]
    LANCE_STROLL: _ClassVar[DriverId]
    ARRON_BARNES: _ClassVar[DriverId]
    MARTIN_GILES: _ClassVar[DriverId]
    ALEX_MURRAY: _ClassVar[DriverId]
    LUCAS_ROTH: _ClassVar[DriverId]
    IGOR_CORREIA: _ClassVar[DriverId]
    SOPHIE_LEVASSEUR: _ClassVar[DriverId]
    JONAS_SCHIFFER: _ClassVar[DriverId]
    ALAIN_FOREST: _ClassVar[DriverId]
    JAY_LETOURNEAU: _ClassVar[DriverId]
    ESTO_SAARI: _ClassVar[DriverId]
    YASAR_ATIYEH: _ClassVar[DriverId]
    CALLISTO_CALABRESI: _ClassVar[DriverId]
    NAOTA_IZUM: _ClassVar[DriverId]
    HOWARD_CLARKE: _ClassVar[DriverId]
    WILHEIM_KAUFMANN: _ClassVar[DriverId]
    MARIE_LAURSEN: _ClassVar[DriverId]
    FLAVIO_NIEVES: _ClassVar[DriverId]
    PETER_BELOUSOV: _ClassVar[DriverId]
    KLIMEK_MICHALSKI: _ClassVar[DriverId]
    SANTIAGO_MORENO: _ClassVar[DriverId]
    BENJAMIN_COPPENS: _ClassVar[DriverId]
    NOAH_VISSER: _ClassVar[DriverId]
    GERT_WALDMULLER: _ClassVar[DriverId]
    JULIAN_QUESADA: _ClassVar[DriverId]
    DANIEL_JONES: _ClassVar[DriverId]
    ARTEM_MARKELOV: _ClassVar[DriverId]
    TADASUKE_MAKINO: _ClassVar[DriverId]
    SEAN_GELAEL: _ClassVar[DriverId]
    NYCK_DE_VRIES: _ClassVar[DriverId]
    JACK_AITKEN: _ClassVar[DriverId]
    GEORGE_RUSSELL: _ClassVar[DriverId]
    MAXIMILIAN_GUNTHER: _ClassVar[DriverId]
    NIREI_FUKUZUMI: _ClassVar[DriverId]
    LUCA_GHIOTTO: _ClassVar[DriverId]
    LANDO_NORRIS: _ClassVar[DriverId]
    SERGIO_SETTE_CAMARA: _ClassVar[DriverId]
    LOUIS_DELETRAZ: _ClassVar[DriverId]
    ANTONIO_FUOCO: _ClassVar[DriverId]
    CHARLES_LECLERC: _ClassVar[DriverId]
    PIERRE_GASLY: _ClassVar[DriverId]
    ALEXANDER_ALBON: _ClassVar[DriverId]
    NICHOLAS_LATIFI: _ClassVar[DriverId]
    DORIAN_BOCCOLACCI: _ClassVar[DriverId]
    NIKO_KARI: _ClassVar[DriverId]
    ROBERTO_MERHI: _ClassVar[DriverId]
    ARJUN_MAINI: _ClassVar[DriverId]
    ALESSIO_LORANDI: _ClassVar[DriverId]
    RUBEN_MEIJER: _ClassVar[DriverId]
    RASHID_NAIR: _ClassVar[DriverId]
    JACK_TREMBLAY: _ClassVar[DriverId]
    DEVON_BUTLER: _ClassVar[DriverId]
    LUKAS_WEBER: _ClassVar[DriverId]
    ANTONIO_GIOVINAZZI: _ClassVar[DriverId]
    ROBERT_KUBICA: _ClassVar[DriverId]
    ALAIN_PROST: _ClassVar[DriverId]
    AYRTON_SENNA: _ClassVar[DriverId]
    NOBUHARU_MATSUSHITA: _ClassVar[DriverId]
    NIKITA_MAZEPIN: _ClassVar[DriverId]
    GUANYA_ZHOU: _ClassVar[DriverId]
    MICK_SCHUMACHER: _ClassVar[DriverId]
    CALLUM_ILOTT: _ClassVar[DriverId]
    JUAN_MANUEL_CORREA: _ClassVar[DriverId]
    JORDAN_KING: _ClassVar[DriverId]
    MAHAVEER_RAGHUNATHAN: _ClassVar[DriverId]
    TATIANA_CALDERON: _ClassVar[DriverId]
    ANTHOINE_HUBERT: _ClassVar[DriverId]
    GUILIANO_ALESI: _ClassVar[DriverId]
    RALPH_BOSCHUNG: _ClassVar[DriverId]
    MICHAEL_SCHUMACHER: _ClassVar[DriverId]
    DAN_TICKTUM: _ClassVar[DriverId]
    MARCUS_ARMSTRONG: _ClassVar[DriverId]
    CHRISTIAN_LUNDGAARD: _ClassVar[DriverId]
    YUKI_TSUNODA: _ClassVar[DriverId]
    JEHAN_DARUVALA: _ClassVar[DriverId]
    GULHERME_SAMAIA: _ClassVar[DriverId]
    PEDRO_PIQUET: _ClassVar[DriverId]
    FELIPE_DRUGOVICH: _ClassVar[DriverId]
    ROBERT_SCHWARTZMAN: _ClassVar[DriverId]
    ROY_NISSANY: _ClassVar[DriverId]
    MARINO_SATO: _ClassVar[DriverId]
    AIDAN_JACKSON: _ClassVar[DriverId]
    CASPER_AKKERMAN: _ClassVar[DriverId]
    JENSON_BUTTON: _ClassVar[DriverId]
    DAVID_COULTHARD: _ClassVar[DriverId]
    NICO_ROSBERG: _ClassVar[DriverId]
    OSCAR_PIASTRI: _ClassVar[DriverId]
    LIAM_LAWSON: _ClassVar[DriverId]
    JURI_VIPS: _ClassVar[DriverId]
    THEO_POURCHAIRE: _ClassVar[DriverId]
    RICHARD_VERSCHOOR: _ClassVar[DriverId]
    LIRIM_ZENDELI: _ClassVar[DriverId]
    DAVID_BECKMANN: _ClassVar[DriverId]
    ALESSIO_DELEDDA: _ClassVar[DriverId]
    BENT_VISCAAL: _ClassVar[DriverId]
    ENZO_FITTIPALDI: _ClassVar[DriverId]
    MARK_WEBBER: _ClassVar[DriverId]
    JACQUES_VILLENEUVE: _ClassVar[DriverId]
    CALLIE_MAYER: _ClassVar[DriverId]
    NOAH_BELL: _ClassVar[DriverId]
    JAKE_HUGHES: _ClassVar[DriverId]
    FREDERIK_VESTI: _ClassVar[DriverId]
    OLLI_CALDWELL: _ClassVar[DriverId]
    LOGAN_SARGEANT: _ClassVar[DriverId]
    CEM_BOLUKBASI: _ClassVar[DriverId]
    AYUMU_IWASA: _ClassVar[DriverId]
    CLEMENT_NOVALAK: _ClassVar[DriverId]
    JACK_DOOHAN: _ClassVar[DriverId]
    AMAURY_CORDEEL: _ClassVar[DriverId]
    DENNIS_HAUGER: _ClassVar[DriverId]
    CALAN_WILLIAMS: _ClassVar[DriverId]
    JAMIE_CHADWICK: _ClassVar[DriverId]
    KAMUI_KOBAYASHI: _ClassVar[DriverId]
    PASTOR_MALDONADO: _ClassVar[DriverId]
    MIKA_HAKKINEN: _ClassVar[DriverId]
    NIGEL_MANSELL: _ClassVar[DriverId]

class TeamId(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    TEAM_ID_UNKNOWN: _ClassVar[TeamId]
    MERCEDES: _ClassVar[TeamId]
    FERRARI: _ClassVar[TeamId]
    RED_BULL_RACING: _ClassVar[TeamId]
    WILLIAMS: _ClassVar[TeamId]
    ASTON_MARTIN: _ClassVar[TeamId]
    ALPINE: _ClassVar[TeamId]
    ALPHA_TAURI: _ClassVar[TeamId]
    HAAS: _ClassVar[TeamId]
    MCLAREN: _ClassVar[TeamId]
    ALFA_ROMEO: _ClassVar[TeamId]
    MERCEDES_2020: _ClassVar[TeamId]
    FERRARI_2020: _ClassVar[TeamId]
    RED_BULL_2020: _ClassVar[TeamId]
    WILLIAMS_2020: _ClassVar[TeamId]
    RACING_POINT_2020: _ClassVar[TeamId]
    RENAULT_2020: _ClassVar[TeamId]
    ALPHA_TAURI_2020: _ClassVar[TeamId]
    HAAS_2020: _ClassVar[TeamId]
    MCLAREN_2020: _ClassVar[TeamId]
    ALFA_ROMEO_2020: _ClassVar[TeamId]
    ASTON_MARTIN_DB11_V12: _ClassVar[TeamId]
    ASTON_MARTIN_VANTAGE_F1_EDITION: _ClassVar[TeamId]
    ASTON_MARTIN_VANTAGE_SAFETY_CAR: _ClassVar[TeamId]
    FERRARI_F8_TRIBUTO: _ClassVar[TeamId]
    FERRARI_ROMA: _ClassVar[TeamId]
    MCLAREN_720S: _ClassVar[TeamId]
    MCLAREN_ARTURA: _ClassVar[TeamId]
    MERCEDES_AMG_GT_BLACK_SERIES_SAFETY_CAR: _ClassVar[TeamId]
    MERCEDES_AMG_GTR_PRO: _ClassVar[TeamId]
    F1_CUSTOM_TEAM: _ClassVar[TeamId]
    PREMA_21: _ClassVar[TeamId]
    UNI_VIRTUOSI_21: _ClassVar[TeamId]
    CARLIN_21: _ClassVar[TeamId]
    HITECH_21: _ClassVar[TeamId]
    ART_GP_21: _ClassVar[TeamId]
    MP_MOTORSPORT_21: _ClassVar[TeamId]
    CHAROUZ_21: _ClassVar[TeamId]
    DAMS_21: _ClassVar[TeamId]
    CAMPOS_21: _ClassVar[TeamId]
    BWT_21: _ClassVar[TeamId]
    TRIDENT_21: _ClassVar[TeamId]
    MERCEDES_AMG_GT_BLACK_SERIES: _ClassVar[TeamId]
    MERCEDES_22: _ClassVar[TeamId]
    FERRARI_22: _ClassVar[TeamId]
    RED_BULL_RACING_22: _ClassVar[TeamId]
    WILLIAMS_22: _ClassVar[TeamId]
    ASTON_MARTIN_22: _ClassVar[TeamId]
    ALPINE_22: _ClassVar[TeamId]
    ALPHA_TAURI_22: _ClassVar[TeamId]
    HAAS_22: _ClassVar[TeamId]
    MCLAREN_22: _ClassVar[TeamId]
    ALFA_ROMEO_22: _ClassVar[TeamId]
    KONNERSPORT_22: _ClassVar[TeamId]
    KONNERSPORT: _ClassVar[TeamId]
    PREMA_22: _ClassVar[TeamId]
    VIRTUOSI_22: _ClassVar[TeamId]
    CARLIN_22: _ClassVar[TeamId]
    MP_MOTORSPORT_22: _ClassVar[TeamId]
    CHAROUZ_22: _ClassVar[TeamId]
    DAMS_22: _ClassVar[TeamId]
    CAMPOS_22: _ClassVar[TeamId]
    VAN_AMERSFOORT_RACING_22: _ClassVar[TeamId]
    TRIDENT_22: _ClassVar[TeamId]
    HITECH_22: _ClassVar[TeamId]
    ART_GP_22: _ClassVar[TeamId]

class NationalityId(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NATIONALITY_ID_UNKNOWN: _ClassVar[NationalityId]
    AMERICAN: _ClassVar[NationalityId]
    ARGENTINEAN: _ClassVar[NationalityId]
    AUSTRALIAN: _ClassVar[NationalityId]
    AUSTRIAN: _ClassVar[NationalityId]
    AZERBAIJANI: _ClassVar[NationalityId]
    BAHRAINI: _ClassVar[NationalityId]
    BELGIAN: _ClassVar[NationalityId]
    BOLIVIAN: _ClassVar[NationalityId]
    BRAZILIAN: _ClassVar[NationalityId]
    BRITISH: _ClassVar[NationalityId]
    BULGARIAN: _ClassVar[NationalityId]
    CAMEROONIAN: _ClassVar[NationalityId]
    CANADIAN: _ClassVar[NationalityId]
    CHILEAN: _ClassVar[NationalityId]
    CHINESE: _ClassVar[NationalityId]
    COLOMBIAN: _ClassVar[NationalityId]
    COSTA_RICAN: _ClassVar[NationalityId]
    CROATIAN: _ClassVar[NationalityId]
    CYPRIOT: _ClassVar[NationalityId]
    CZECH: _ClassVar[NationalityId]
    DANISH: _ClassVar[NationalityId]
    DUTCH: _ClassVar[NationalityId]
    ECUADORIAN: _ClassVar[NationalityId]
    ENGLISH: _ClassVar[NationalityId]
    EMIRIAN: _ClassVar[NationalityId]
    ESTONIAN: _ClassVar[NationalityId]
    FINNISH: _ClassVar[NationalityId]
    FRENCH: _ClassVar[NationalityId]
    GERMAN: _ClassVar[NationalityId]
    GHANAIAN: _ClassVar[NationalityId]
    GREEK: _ClassVar[NationalityId]
    GUATEMALAN: _ClassVar[NationalityId]
    HONDURAN: _ClassVar[NationalityId]
    HONG_KONGER: _ClassVar[NationalityId]
    HUNGARIAN: _ClassVar[NationalityId]
    ICELANDER: _ClassVar[NationalityId]
    INDIAN: _ClassVar[NationalityId]
    INDONESIAN: _ClassVar[NationalityId]
    IRISH: _ClassVar[NationalityId]
    ISRAELI: _ClassVar[NationalityId]
    ITALIAN: _ClassVar[NationalityId]
    JAMAICAN: _ClassVar[NationalityId]
    JAPANESE: _ClassVar[NationalityId]
    JORDANIAN: _ClassVar[NationalityId]
    KUWAITI: _ClassVar[NationalityId]
    LATVIAN: _ClassVar[NationalityId]
    LEBANESE: _ClassVar[NationalityId]
    LITHUANIAN: _ClassVar[NationalityId]
    LUXEMBOURGER: _ClassVar[NationalityId]
    MALAYSIAN: _ClassVar[NationalityId]
    MALTESE: _ClassVar[NationalityId]
    MEXICAN: _ClassVar[NationalityId]
    MONEGASQUE: _ClassVar[NationalityId]
    NEW_ZEALANDER: _ClassVar[NationalityId]
    NICARAGUAN: _ClassVar[NationalityId]
    NORTHERN_IRISH: _ClassVar[NationalityId]
    NORWEGIAN: _ClassVar[NationalityId]
    OMANI: _ClassVar[NationalityId]
    PAKISTANI: _ClassVar[NationalityId]
    PANAMANIAN: _ClassVar[NationalityId]
    PARAGUAYAN: _ClassVar[NationalityId]
    PERUVIAN: _ClassVar[NationalityId]
    POLISH: _ClassVar[NationalityId]
    PORTUGUESE: _ClassVar[NationalityId]
    QATARI: _ClassVar[NationalityId]
    ROMANIAN: _ClassVar[NationalityId]
    RUSSIAN: _ClassVar[NationalityId]
    SALVADORAN: _ClassVar[NationalityId]
    SAUDI: _ClassVar[NationalityId]
    SCOTTISH: _ClassVar[NationalityId]
    SERBIAN: _ClassVar[NationalityId]
    SINGAPOREAN: _ClassVar[NationalityId]
    SLOVAKIAN: _ClassVar[NationalityId]
    SLOVENIAN: _ClassVar[NationalityId]
    SOUTH_KOREAN: _ClassVar[NationalityId]
    SOUTH_AFRICAN: _ClassVar[NationalityId]
    SPANISH: _ClassVar[NationalityId]
    SWEDISH: _ClassVar[NationalityId]
    SWISS: _ClassVar[NationalityId]
    THAI: _ClassVar[NationalityId]
    TURKISH: _ClassVar[NationalityId]
    URUGUAYAN: _ClassVar[NationalityId]
    UKRAINIAN: _ClassVar[NationalityId]
    VENEZUELAN: _ClassVar[NationalityId]
    BARBADIAN: _ClassVar[NationalityId]
    WELSH: _ClassVar[NationalityId]
    VIETNAMESE: _ClassVar[NationalityId]

class SurfaceType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SURFACE_TYPE_TARMAC: _ClassVar[SurfaceType]
    RUMBLE_STRIP: _ClassVar[SurfaceType]
    CONCRETE: _ClassVar[SurfaceType]
    ROCK: _ClassVar[SurfaceType]
    GRAVEL: _ClassVar[SurfaceType]
    MUD: _ClassVar[SurfaceType]
    SAND: _ClassVar[SurfaceType]
    GRASS: _ClassVar[SurfaceType]
    WATER: _ClassVar[SurfaceType]
    COBBLESTONE: _ClassVar[SurfaceType]
    METAL: _ClassVar[SurfaceType]
    RIDGED: _ClassVar[SurfaceType]

class PitLimiterStatus(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PIT_LIMITER_OFF: _ClassVar[PitLimiterStatus]
    PIT_LIMITER_ON: _ClassVar[PitLimiterStatus]

class DrsAllowedStatus(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    DRS_UNKNOWN: _ClassVar[DrsAllowedStatus]
    DRS_NOT_ALLOWED: _ClassVar[DrsAllowedStatus]
    DRS_ALLOWED: _ClassVar[DrsAllowedStatus]

class ActualTyreCompound(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ACTUAL_TYRE_COMPOUND_UNKNOWN: _ClassVar[ActualTyreCompound]
    INTER: _ClassVar[ActualTyreCompound]
    WET: _ClassVar[ActualTyreCompound]
    C5: _ClassVar[ActualTyreCompound]
    C4: _ClassVar[ActualTyreCompound]
    C3: _ClassVar[ActualTyreCompound]
    C2: _ClassVar[ActualTyreCompound]
    C1: _ClassVar[ActualTyreCompound]
    C0: _ClassVar[ActualTyreCompound]

class VisualTyreCompound(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    VISUAL_TYRE_COMPOUND_UNKNOWN: _ClassVar[VisualTyreCompound]
    VISUAL_INTER: _ClassVar[VisualTyreCompound]
    VISUAL_WET: _ClassVar[VisualTyreCompound]
    SOFT: _ClassVar[VisualTyreCompound]
    MEDIUM: _ClassVar[VisualTyreCompound]
    HARD: _ClassVar[VisualTyreCompound]

class VehicleFiaFlag(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    FIA_FLAG_INVALID: _ClassVar[VehicleFiaFlag]
    FIA_FLAG_NONE: _ClassVar[VehicleFiaFlag]
    FIA_FLAG_GREEN: _ClassVar[VehicleFiaFlag]
    FIA_FLAG_BLUE: _ClassVar[VehicleFiaFlag]
    FIA_FLAG_YELLOW: _ClassVar[VehicleFiaFlag]

class ErsDeployMode(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ERS_NONE: _ClassVar[ErsDeployMode]
    ERS_MEDIUM: _ClassVar[ErsDeployMode]
    ERS_HOTLAP: _ClassVar[ErsDeployMode]
    ERS_OVERTAKE: _ClassVar[ErsDeployMode]

class NetworkPausedStatus(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NOT_PAUSED: _ClassVar[NetworkPausedStatus]
    PAUSED: _ClassVar[NetworkPausedStatus]
PACKET_TYPE_UNSPECIFIED: PacketType
PACKET_MOTION_DATA: PacketType
PACKET_SESSION_DATA: PacketType
PACKET_LAP_DATA: PacketType
PACKET_EVENT_DATA: PacketType
PACKET_PARTICIPANTS_DATA: PacketType
PACKET_CAR_SETUP_DATA: PacketType
PACKET_CAR_TELEMETRY_DATA: PacketType
PACKET_CAR_STATUS_DATA: PacketType
PACKET_FINAL_CLASSIFICATION_DATA: PacketType
PACKET_LOBBY_INFO_DATA: PacketType
PACKET_CAR_DAMAGE_DATA: PacketType
PACKET_SESSION_HISTORY_DATA: PacketType
PACKET_TYRE_SETS_DATA: PacketType
PACKET_MOTION_EX_DATA: PacketType
WEATHER_UNSPECIFIED: Weather
CLEAR: Weather
LIGHT_CLOUD: Weather
OVERCAST: Weather
LIGHT_RAIN: Weather
HEAVY_RAIN: Weather
STORM: Weather
SESSION_TYPE_UNKNOWN: SessionType
P1: SessionType
P2: SessionType
P3: SessionType
SHORT_P: SessionType
Q1: SessionType
Q2: SessionType
Q3: SessionType
SHORT_Q: SessionType
OSQ: SessionType
R: SessionType
R2: SessionType
R3: SessionType
TIME_TRIAL: SessionType
TRACK_ID_UNKNOWN: TrackId
MELBOURNE: TrackId
PAUL_RICARD: TrackId
SHANGHAI: TrackId
SAKHIR_BAHRAIN: TrackId
CATALUNYA: TrackId
MONACO: TrackId
MONTREAL: TrackId
SILVERSTONE: TrackId
HOCKENHEIM: TrackId
HUNGARORING: TrackId
SPA: TrackId
MONZA: TrackId
SINGAPORE: TrackId
SUZUKA: TrackId
ABU_DHABI: TrackId
TEXAS: TrackId
BRAZIL: TrackId
AUSTRIA: TrackId
SOCHI: TrackId
MEXICO: TrackId
BAKU_AZERBAIJAN: TrackId
SAKHIR_SHORT: TrackId
SILVERSTONE_SHORT: TrackId
TEXAS_SHORT: TrackId
SUZUKA_SHORT: TrackId
HANOI: TrackId
ZANDVOORT: TrackId
IMOLA: TrackId
PORTIMAO: TrackId
JEDDAH: TrackId
MIAMI: TrackId
LAS_VEGAS: TrackId
LOSAIL: TrackId
TEMPERATURE_CHANGE_UNSPECIFIED: TemperatureChange
UP: TemperatureChange
DOWN: TemperatureChange
NO_CHANGE: TemperatureChange
SAFETY_CAR_STATUS_UNSPECIFIED: SafetyCarStatus
NO_SAFETY_CAR: SafetyCarStatus
FULL_SAFETY_CAR: SafetyCarStatus
VIRTUAL_SAFETY_CAR: SafetyCarStatus
FORMATION_LAP: SafetyCarStatus
PIT_STATUS_NONE: PitStatus
PITTING: PitStatus
IN_PIT_AREA: PitStatus
SECTOR_UNSPECIFIED: Sector
SECTOR1: Sector
SECTOR2: Sector
SECTOR3: Sector
VALID: LapValidity
INVALID: LapValidity
RESULT_STATUS_INVALID: ResultStatus
INACTIVE: ResultStatus
ACTIVE: ResultStatus
FINISHED: ResultStatus
DNF: ResultStatus
DSQ: ResultStatus
NOT_CLASSIFIED: ResultStatus
RETIRED: ResultStatus
NO: PitStopShouldServePenalty
YES: PitStopShouldServePenalty
EVENT_TYPE_UNSPECIFIED: EventType
SESSION_STARTED: EventType
SESSION_ENDED: EventType
FASTEST_LAP: EventType
RETIREMENT: EventType
DRS_ENABLED: EventType
DRS_DISABLED: EventType
TEAM_MATE_IN_PITS: EventType
CHEQUERED_FLAG: EventType
RACE_WINNER: EventType
PENALTY_ISSUED: EventType
SPEED_TRAP_TRIGGERED: EventType
START_LIGHT: EventType
LIGHTS_OUT: EventType
DRIVE_THROUGH_SERVED: EventType
STOP_GO_SERVED: EventType
FLASHBACK: EventType
BUTTON_STATUS: EventType
RED_FLAG: EventType
OVERTAKE: EventType
UNKNOWN: EventType
PENALTY_TYPE_UNSPECIFIED: PenaltyType
DRIVE_THROUGH: PenaltyType
STOP_GO: PenaltyType
GRID_PENALTY: PenaltyType
PENALTY_REMINDER: PenaltyType
TIME_PENALTY: PenaltyType
WARNING: PenaltyType
DISQUALIFIED: PenaltyType
REMOVED_FROM_FORMATION_LAP: PenaltyType
PARKED_TOO_LONG_TIMER: PenaltyType
TYRE_REGULATIONS: PenaltyType
THIS_LAP_INVALIDATED: PenaltyType
THIS_AND_NEXT_LAP_INVALIDATED: PenaltyType
THIS_LAP_INVALIDATED_WITHOUT_REASON: PenaltyType
THIS_AND_NEXT_LAP_INVALIDATED_WITHOUT_REASON: PenaltyType
THIS_AND_PREVIOUS_LAP_INVALIDATED: PenaltyType
THIS_AND_PREVIOUS_LAP_INVALIDATED_WITHOUT_REASON: PenaltyType
RETIRED_PENALTY: PenaltyType
BLACK_FLAG_TIMER: PenaltyType
INFRINGEMENT_TYPE_UNSPECIFIED: InfringementType
BLOCKING_BY_SLOW_DRIVING: InfringementType
BLOCKING_BY_WRONG_WAY_DRIVING: InfringementType
REVERSING_OFF_THE_START_LINE: InfringementType
BIG_COLLISION: InfringementType
SMALL_COLLISION: InfringementType
COLLISION_FAILED_TO_HAND_BACK_POSITION_SINGLE: InfringementType
COLLISION_FAILED_TO_HAND_BACK_POSITION_MULTIPLE: InfringementType
CORNER_CUTTING_GAINED_TIME: InfringementType
CORNER_CUTTING_OVERTAKE_SINGLE: InfringementType
CORNER_CUTTING_OVERTAKE_MULTIPLE: InfringementType
CROSSED_PIT_EXIT_LANE: InfringementType
IGNORING_BLUE_FLAGS: InfringementType
IGNORING_YELLOW_FLAGS: InfringementType
IGNORING_DRIVE_THROUGH: InfringementType
TOO_MANY_DRIVE_THROUGHS: InfringementType
DRIVE_THROUGH_REMINDER_SERVE_WITHIN_N_LAPS: InfringementType
DRIVE_THROUGH_REMINDER_SERVE_THIS_LAP: InfringementType
PIT_LANE_SPEEDING: InfringementType
PARKED_FOR_TOO_LONG: InfringementType
IGNORING_TYRE_REGULATIONS: InfringementType
TOO_MANY_PENALTIES: InfringementType
MULTIPLE_WARNINGS: InfringementType
APPROACHING_DISQUALIFICATION: InfringementType
TYRE_REGULATIONS_SELECT_SINGLE: InfringementType
TYRE_REGULATIONS_SELECT_MULTIPLE: InfringementType
LAP_INVALIDATED_CORNER_CUTTING: InfringementType
LAP_INVALIDATED_RUNNING_WIDE: InfringementType
CORNER_CUTTING_RAN_WIDE_GAINED_TIME_MINOR: InfringementType
CORNER_CUTTING_RAN_WIDE_GAINED_TIME_SIGNIFICANT: InfringementType
CORNER_CUTTING_RAN_WIDE_GAINED_TIME_EXTREME: InfringementType
LAP_INVALIDATED_WALL_RIDING: InfringementType
LAP_INVALIDATED_FLASHBACK_USED: InfringementType
LAP_INVALIDATED_RESET_TO_TRACK: InfringementType
BLOCKING_THE_PITLANE: InfringementType
JUMP_START: InfringementType
SAFETY_CAR_TO_CAR_COLLISION: InfringementType
SAFETY_CAR_ILLEGAL_OVERTAKE: InfringementType
SAFETY_CAR_EXCEEDING_ALLOWED_PACE: InfringementType
VIRTUAL_SAFETY_CAR_EXCEEDING_ALLOWED_PACE: InfringementType
FORMATION_LAP_BELOW_ALLOWED_SPEED: InfringementType
FORMATION_LAP_PARKING: InfringementType
RETIRED_MECHANICAL_FAILURE: InfringementType
RETIRED_TERMINALLY_DAMAGED: InfringementType
SAFETY_CAR_FALLING_TOO_FAR_BACK: InfringementType
BLACK_FLAG_TIMER_INFRINGEMENT: InfringementType
UNSERVED_STOP_GO_PENALTY: InfringementType
UNSERVED_DRIVE_THROUGH_PENALTY: InfringementType
ENGINE_COMPONENT_CHANGE: InfringementType
GEARBOX_CHANGE: InfringementType
PARC_FERME_CHANGE: InfringementType
LEAGUE_GRID_PENALTY: InfringementType
RETRY_PENALTY: InfringementType
ILLEGAL_TIME_GAIN: InfringementType
MANDATORY_PITSTOP: InfringementType
ATTRIBUTE_ASSIGNED: InfringementType
DRIVER_ID_UNKNOWN: DriverId
CARLOS_SAINZ: DriverId
DANIIL_KVYAT: DriverId
DANIEL_RICCIARDO: DriverId
FERNANDO_ALONSO: DriverId
FELIPE_MASSA: DriverId
KIMI_RAIKKONEN: DriverId
LEWIS_HAMILTON: DriverId
MAX_VERSTAPPEN: DriverId
NICO_HULKENBURG: DriverId
KEVIN_MAGNUSSEN: DriverId
ROMAIN_GROSJEAN: DriverId
SEBASTIAN_VETTEL: DriverId
SERGIO_PEREZ: DriverId
VALTTERI_BOTTAS: DriverId
ESTEBAN_OCON: DriverId
LANCE_STROLL: DriverId
ARRON_BARNES: DriverId
MARTIN_GILES: DriverId
ALEX_MURRAY: DriverId
LUCAS_ROTH: DriverId
IGOR_CORREIA: DriverId
SOPHIE_LEVASSEUR: DriverId
JONAS_SCHIFFER: DriverId
ALAIN_FOREST: DriverId
JAY_LETOURNEAU: DriverId
ESTO_SAARI: DriverId
YASAR_ATIYEH: DriverId
CALLISTO_CALABRESI: DriverId
NAOTA_IZUM: DriverId
HOWARD_CLARKE: DriverId
WILHEIM_KAUFMANN: DriverId
MARIE_LAURSEN: DriverId
FLAVIO_NIEVES: DriverId
PETER_BELOUSOV: DriverId
KLIMEK_MICHALSKI: DriverId
SANTIAGO_MORENO: DriverId
BENJAMIN_COPPENS: DriverId
NOAH_VISSER: DriverId
GERT_WALDMULLER: DriverId
JULIAN_QUESADA: DriverId
DANIEL_JONES: DriverId
ARTEM_MARKELOV: DriverId
TADASUKE_MAKINO: DriverId
SEAN_GELAEL: DriverId
NYCK_DE_VRIES: DriverId
JACK_AITKEN: DriverId
GEORGE_RUSSELL: DriverId
MAXIMILIAN_GUNTHER: DriverId
NIREI_FUKUZUMI: DriverId
LUCA_GHIOTTO: DriverId
LANDO_NORRIS: DriverId
SERGIO_SETTE_CAMARA: DriverId
LOUIS_DELETRAZ: DriverId
ANTONIO_FUOCO: DriverId
CHARLES_LECLERC: DriverId
PIERRE_GASLY: DriverId
ALEXANDER_ALBON: DriverId
NICHOLAS_LATIFI: DriverId
DORIAN_BOCCOLACCI: DriverId
NIKO_KARI: DriverId
ROBERTO_MERHI: DriverId
ARJUN_MAINI: DriverId
ALESSIO_LORANDI: DriverId
RUBEN_MEIJER: DriverId
RASHID_NAIR: DriverId
JACK_TREMBLAY: DriverId
DEVON_BUTLER: DriverId
LUKAS_WEBER: DriverId
ANTONIO_GIOVINAZZI: DriverId
ROBERT_KUBICA: DriverId
ALAIN_PROST: DriverId
AYRTON_SENNA: DriverId
NOBUHARU_MATSUSHITA: DriverId
NIKITA_MAZEPIN: DriverId
GUANYA_ZHOU: DriverId
MICK_SCHUMACHER: DriverId
CALLUM_ILOTT: DriverId
JUAN_MANUEL_CORREA: DriverId
JORDAN_KING: DriverId
MAHAVEER_RAGHUNATHAN: DriverId
TATIANA_CALDERON: DriverId
ANTHOINE_HUBERT: DriverId
GUILIANO_ALESI: DriverId
RALPH_BOSCHUNG: DriverId
MICHAEL_SCHUMACHER: DriverId
DAN_TICKTUM: DriverId
MARCUS_ARMSTRONG: DriverId
CHRISTIAN_LUNDGAARD: DriverId
YUKI_TSUNODA: DriverId
JEHAN_DARUVALA: DriverId
GULHERME_SAMAIA: DriverId
PEDRO_PIQUET: DriverId
FELIPE_DRUGOVICH: DriverId
ROBERT_SCHWARTZMAN: DriverId
ROY_NISSANY: DriverId
MARINO_SATO: DriverId
AIDAN_JACKSON: DriverId
CASPER_AKKERMAN: DriverId
JENSON_BUTTON: DriverId
DAVID_COULTHARD: DriverId
NICO_ROSBERG: DriverId
OSCAR_PIASTRI: DriverId
LIAM_LAWSON: DriverId
JURI_VIPS: DriverId
THEO_POURCHAIRE: DriverId
RICHARD_VERSCHOOR: DriverId
LIRIM_ZENDELI: DriverId
DAVID_BECKMANN: DriverId
ALESSIO_DELEDDA: DriverId
BENT_VISCAAL: DriverId
ENZO_FITTIPALDI: DriverId
MARK_WEBBER: DriverId
JACQUES_VILLENEUVE: DriverId
CALLIE_MAYER: DriverId
NOAH_BELL: DriverId
JAKE_HUGHES: DriverId
FREDERIK_VESTI: DriverId
OLLI_CALDWELL: DriverId
LOGAN_SARGEANT: DriverId
CEM_BOLUKBASI: DriverId
AYUMU_IWASA: DriverId
CLEMENT_NOVALAK: DriverId
JACK_DOOHAN: DriverId
AMAURY_CORDEEL: DriverId
DENNIS_HAUGER: DriverId
CALAN_WILLIAMS: DriverId
JAMIE_CHADWICK: DriverId
KAMUI_KOBAYASHI: DriverId
PASTOR_MALDONADO: DriverId
MIKA_HAKKINEN: DriverId
NIGEL_MANSELL: DriverId
TEAM_ID_UNKNOWN: TeamId
MERCEDES: TeamId
FERRARI: TeamId
RED_BULL_RACING: TeamId
WILLIAMS: TeamId
ASTON_MARTIN: TeamId
ALPINE: TeamId
ALPHA_TAURI: TeamId
HAAS: TeamId
MCLAREN: TeamId
ALFA_ROMEO: TeamId
MERCEDES_2020: TeamId
FERRARI_2020: TeamId
RED_BULL_2020: TeamId
WILLIAMS_2020: TeamId
RACING_POINT_2020: TeamId
RENAULT_2020: TeamId
ALPHA_TAURI_2020: TeamId
HAAS_2020: TeamId
MCLAREN_2020: TeamId
ALFA_ROMEO_2020: TeamId
ASTON_MARTIN_DB11_V12: TeamId
ASTON_MARTIN_VANTAGE_F1_EDITION: TeamId
ASTON_MARTIN_VANTAGE_SAFETY_CAR: TeamId
FERRARI_F8_TRIBUTO: TeamId
FERRARI_ROMA: TeamId
MCLAREN_720S: TeamId
MCLAREN_ARTURA: TeamId
MERCEDES_AMG_GT_BLACK_SERIES_SAFETY_CAR: TeamId
MERCEDES_AMG_GTR_PRO: TeamId
F1_CUSTOM_TEAM: TeamId
PREMA_21: TeamId
UNI_VIRTUOSI_21: TeamId
CARLIN_21: TeamId
HITECH_21: TeamId
ART_GP_21: TeamId
MP_MOTORSPORT_21: TeamId
CHAROUZ_21: TeamId
DAMS_21: TeamId
CAMPOS_21: TeamId
BWT_21: TeamId
TRIDENT_21: TeamId
MERCEDES_AMG_GT_BLACK_SERIES: TeamId
MERCEDES_22: TeamId
FERRARI_22: TeamId
RED_BULL_RACING_22: TeamId
WILLIAMS_22: TeamId
ASTON_MARTIN_22: TeamId
ALPINE_22: TeamId
ALPHA_TAURI_22: TeamId
HAAS_22: TeamId
MCLAREN_22: TeamId
ALFA_ROMEO_22: TeamId
KONNERSPORT_22: TeamId
KONNERSPORT: TeamId
PREMA_22: TeamId
VIRTUOSI_22: TeamId
CARLIN_22: TeamId
MP_MOTORSPORT_22: TeamId
CHAROUZ_22: TeamId
DAMS_22: TeamId
CAMPOS_22: TeamId
VAN_AMERSFOORT_RACING_22: TeamId
TRIDENT_22: TeamId
HITECH_22: TeamId
ART_GP_22: TeamId
NATIONALITY_ID_UNKNOWN: NationalityId
AMERICAN: NationalityId
ARGENTINEAN: NationalityId
AUSTRALIAN: NationalityId
AUSTRIAN: NationalityId
AZERBAIJANI: NationalityId
BAHRAINI: NationalityId
BELGIAN: NationalityId
BOLIVIAN: NationalityId
BRAZILIAN: NationalityId
BRITISH: NationalityId
BULGARIAN: NationalityId
CAMEROONIAN: NationalityId
CANADIAN: NationalityId
CHILEAN: NationalityId
CHINESE: NationalityId
COLOMBIAN: NationalityId
COSTA_RICAN: NationalityId
CROATIAN: NationalityId
CYPRIOT: NationalityId
CZECH: NationalityId
DANISH: NationalityId
DUTCH: NationalityId
ECUADORIAN: NationalityId
ENGLISH: NationalityId
EMIRIAN: NationalityId
ESTONIAN: NationalityId
FINNISH: NationalityId
FRENCH: NationalityId
GERMAN: NationalityId
GHANAIAN: NationalityId
GREEK: NationalityId
GUATEMALAN: NationalityId
HONDURAN: NationalityId
HONG_KONGER: NationalityId
HUNGARIAN: NationalityId
ICELANDER: NationalityId
INDIAN: NationalityId
INDONESIAN: NationalityId
IRISH: NationalityId
ISRAELI: NationalityId
ITALIAN: NationalityId
JAMAICAN: NationalityId
JAPANESE: NationalityId
JORDANIAN: NationalityId
KUWAITI: NationalityId
LATVIAN: NationalityId
LEBANESE: NationalityId
LITHUANIAN: NationalityId
LUXEMBOURGER: NationalityId
MALAYSIAN: NationalityId
MALTESE: NationalityId
MEXICAN: NationalityId
MONEGASQUE: NationalityId
NEW_ZEALANDER: NationalityId
NICARAGUAN: NationalityId
NORTHERN_IRISH: NationalityId
NORWEGIAN: NationalityId
OMANI: NationalityId
PAKISTANI: NationalityId
PANAMANIAN: NationalityId
PARAGUAYAN: NationalityId
PERUVIAN: NationalityId
POLISH: NationalityId
PORTUGUESE: NationalityId
QATARI: NationalityId
ROMANIAN: NationalityId
RUSSIAN: NationalityId
SALVADORAN: NationalityId
SAUDI: NationalityId
SCOTTISH: NationalityId
SERBIAN: NationalityId
SINGAPOREAN: NationalityId
SLOVAKIAN: NationalityId
SLOVENIAN: NationalityId
SOUTH_KOREAN: NationalityId
SOUTH_AFRICAN: NationalityId
SPANISH: NationalityId
SWEDISH: NationalityId
SWISS: NationalityId
THAI: NationalityId
TURKISH: NationalityId
URUGUAYAN: NationalityId
UKRAINIAN: NationalityId
VENEZUELAN: NationalityId
BARBADIAN: NationalityId
WELSH: NationalityId
VIETNAMESE: NationalityId
SURFACE_TYPE_TARMAC: SurfaceType
RUMBLE_STRIP: SurfaceType
CONCRETE: SurfaceType
ROCK: SurfaceType
GRAVEL: SurfaceType
MUD: SurfaceType
SAND: SurfaceType
GRASS: SurfaceType
WATER: SurfaceType
COBBLESTONE: SurfaceType
METAL: SurfaceType
RIDGED: SurfaceType
PIT_LIMITER_OFF: PitLimiterStatus
PIT_LIMITER_ON: PitLimiterStatus
DRS_UNKNOWN: DrsAllowedStatus
DRS_NOT_ALLOWED: DrsAllowedStatus
DRS_ALLOWED: DrsAllowedStatus
ACTUAL_TYRE_COMPOUND_UNKNOWN: ActualTyreCompound
INTER: ActualTyreCompound
WET: ActualTyreCompound
C5: ActualTyreCompound
C4: ActualTyreCompound
C3: ActualTyreCompound
C2: ActualTyreCompound
C1: ActualTyreCompound
C0: ActualTyreCompound
VISUAL_TYRE_COMPOUND_UNKNOWN: VisualTyreCompound
VISUAL_INTER: VisualTyreCompound
VISUAL_WET: VisualTyreCompound
SOFT: VisualTyreCompound
MEDIUM: VisualTyreCompound
HARD: VisualTyreCompound
FIA_FLAG_INVALID: VehicleFiaFlag
FIA_FLAG_NONE: VehicleFiaFlag
FIA_FLAG_GREEN: VehicleFiaFlag
FIA_FLAG_BLUE: VehicleFiaFlag
FIA_FLAG_YELLOW: VehicleFiaFlag
ERS_NONE: ErsDeployMode
ERS_MEDIUM: ErsDeployMode
ERS_HOTLAP: ErsDeployMode
ERS_OVERTAKE: ErsDeployMode
NOT_PAUSED: NetworkPausedStatus
PAUSED: NetworkPausedStatus
